// Generated by delombok at Sat Sep 26 12:28:47 IST 2026
package com.campus.complaint.dto.response;

import com.campus.complaint.entity.Complaint;
import java.time.LocalDateTime;

public class ComplaintResponse {
    private Long id;
    private String complaintId;
    private StudentInfo student;
    private String title;
    private String description;
    private String category;
    private String priority;
    private DepartmentInfo department;
    private AdminInfo assignedHandler;
    private String status;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
    private LocalDateTime dueDate;
    private LocalDateTime resolvedAt;
    private LocalDateTime closedAt;
    private String rejectionReason;
    private String resolutionNote;
    private boolean overdue;
    private Long hoursRemaining;
    private java.util.List<ComplaintAttachmentResponse> attachments = new java.util.ArrayList<>();


    public static class StudentInfo {
        private Long id;
        private String studentId;
        private String fullName;
        private String email;
        private String department;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public StudentInfo() {
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Long getId() {
            return this.id;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public String getStudentId() {
            return this.studentId;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public String getFullName() {
            return this.fullName;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public String getEmail() {
            return this.email;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public String getDepartment() {
            return this.department;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setId(final Long id) {
            this.id = id;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setStudentId(final String studentId) {
            this.studentId = studentId;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setFullName(final String fullName) {
            this.fullName = fullName;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setEmail(final String email) {
            this.email = email;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setDepartment(final String department) {
            this.department = department;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof ComplaintResponse.StudentInfo)) return false;
            final ComplaintResponse.StudentInfo other = (ComplaintResponse.StudentInfo) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$id = this.getId();
            final java.lang.Object other$id = other.getId();
            if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
            final java.lang.Object this$studentId = this.getStudentId();
            final java.lang.Object other$studentId = other.getStudentId();
            if (this$studentId == null ? other$studentId != null : !this$studentId.equals(other$studentId)) return false;
            final java.lang.Object this$fullName = this.getFullName();
            final java.lang.Object other$fullName = other.getFullName();
            if (this$fullName == null ? other$fullName != null : !this$fullName.equals(other$fullName)) return false;
            final java.lang.Object this$email = this.getEmail();
            final java.lang.Object other$email = other.getEmail();
            if (this$email == null ? other$email != null : !this$email.equals(other$email)) return false;
            final java.lang.Object this$department = this.getDepartment();
            final java.lang.Object other$department = other.getDepartment();
            if (this$department == null ? other$department != null : !this$department.equals(other$department)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof ComplaintResponse.StudentInfo;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $id = this.getId();
            result = result * PRIME + ($id == null ? 43 : $id.hashCode());
            final java.lang.Object $studentId = this.getStudentId();
            result = result * PRIME + ($studentId == null ? 43 : $studentId.hashCode());
            final java.lang.Object $fullName = this.getFullName();
            result = result * PRIME + ($fullName == null ? 43 : $fullName.hashCode());
            final java.lang.Object $email = this.getEmail();
            result = result * PRIME + ($email == null ? 43 : $email.hashCode());
            final java.lang.Object $department = this.getDepartment();
            result = result * PRIME + ($department == null ? 43 : $department.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "ComplaintResponse.StudentInfo(id=" + this.getId() + ", studentId=" + this.getStudentId() + ", fullName=" + this.getFullName() + ", email=" + this.getEmail() + ", department=" + this.getDepartment() + ")";
        }
    }


    public static class AdminInfo {
        private Long id;
        private String username;
        private String fullName;
        private String email;
        private String role;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public AdminInfo() {
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Long getId() {
            return this.id;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public String getUsername() {
            return this.username;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public String getFullName() {
            return this.fullName;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public String getEmail() {
            return this.email;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public String getRole() {
            return this.role;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setId(final Long id) {
            this.id = id;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setUsername(final String username) {
            this.username = username;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setFullName(final String fullName) {
            this.fullName = fullName;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setEmail(final String email) {
            this.email = email;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setRole(final String role) {
            this.role = role;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof ComplaintResponse.AdminInfo)) return false;
            final ComplaintResponse.AdminInfo other = (ComplaintResponse.AdminInfo) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$id = this.getId();
            final java.lang.Object other$id = other.getId();
            if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
            final java.lang.Object this$username = this.getUsername();
            final java.lang.Object other$username = other.getUsername();
            if (this$username == null ? other$username != null : !this$username.equals(other$username)) return false;
            final java.lang.Object this$fullName = this.getFullName();
            final java.lang.Object other$fullName = other.getFullName();
            if (this$fullName == null ? other$fullName != null : !this$fullName.equals(other$fullName)) return false;
            final java.lang.Object this$email = this.getEmail();
            final java.lang.Object other$email = other.getEmail();
            if (this$email == null ? other$email != null : !this$email.equals(other$email)) return false;
            final java.lang.Object this$role = this.getRole();
            final java.lang.Object other$role = other.getRole();
            if (this$role == null ? other$role != null : !this$role.equals(other$role)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof ComplaintResponse.AdminInfo;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $id = this.getId();
            result = result * PRIME + ($id == null ? 43 : $id.hashCode());
            final java.lang.Object $username = this.getUsername();
            result = result * PRIME + ($username == null ? 43 : $username.hashCode());
            final java.lang.Object $fullName = this.getFullName();
            result = result * PRIME + ($fullName == null ? 43 : $fullName.hashCode());
            final java.lang.Object $email = this.getEmail();
            result = result * PRIME + ($email == null ? 43 : $email.hashCode());
            final java.lang.Object $role = this.getRole();
            result = result * PRIME + ($role == null ? 43 : $role.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "ComplaintResponse.AdminInfo(id=" + this.getId() + ", username=" + this.getUsername() + ", fullName=" + this.getFullName() + ", email=" + this.getEmail() + ", role=" + this.getRole() + ")";
        }
    }


    public static class DepartmentInfo {
        private Long id;
        private String name;
        private String code;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public DepartmentInfo() {
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Long getId() {
            return this.id;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public String getName() {
            return this.name;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public String getCode() {
            return this.code;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setId(final Long id) {
            this.id = id;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setName(final String name) {
            this.name = name;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setCode(final String code) {
            this.code = code;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof ComplaintResponse.DepartmentInfo)) return false;
            final ComplaintResponse.DepartmentInfo other = (ComplaintResponse.DepartmentInfo) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$id = this.getId();
            final java.lang.Object other$id = other.getId();
            if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
            final java.lang.Object this$name = this.getName();
            final java.lang.Object other$name = other.getName();
            if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
            final java.lang.Object this$code = this.getCode();
            final java.lang.Object other$code = other.getCode();
            if (this$code == null ? other$code != null : !this$code.equals(other$code)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof ComplaintResponse.DepartmentInfo;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $id = this.getId();
            result = result * PRIME + ($id == null ? 43 : $id.hashCode());
            final java.lang.Object $name = this.getName();
            result = result * PRIME + ($name == null ? 43 : $name.hashCode());
            final java.lang.Object $code = this.getCode();
            result = result * PRIME + ($code == null ? 43 : $code.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "ComplaintResponse.DepartmentInfo(id=" + this.getId() + ", name=" + this.getName() + ", code=" + this.getCode() + ")";
        }
    }

    public static ComplaintResponse from(Complaint c) {
        ComplaintResponse r = new ComplaintResponse();
        r.setId(c.getId());
        r.setComplaintId(c.getComplaintId());
        r.setTitle(c.getTitle());
        r.setDescription(c.getDescription());
        r.setCategory(c.getCategory().name());
        r.setPriority(c.getPriority().name());
        r.setStatus(c.getStatus().name());
        r.setCreatedAt(c.getCreatedAt());
        r.setUpdatedAt(c.getUpdatedAt());
        r.setDueDate(c.getDueDate());
        r.setResolvedAt(c.getResolvedAt());
        r.setClosedAt(c.getClosedAt());
        r.setRejectionReason(c.getRejectionReason());
        r.setResolutionNote(c.getResolutionNote());
        if (c.getStudent() != null) {
            StudentInfo si = new StudentInfo();
            si.setId(c.getStudent().getId());
            si.setStudentId(c.getStudent().getStudentId());
            si.setFullName(c.getStudent().getFullName());
            si.setEmail(c.getStudent().getEmail());
            si.setDepartment(c.getStudent().getDepartment());
            r.setStudent(si);
        }
        if (c.getDepartment() != null) {
            DepartmentInfo di = new DepartmentInfo();
            di.setId(c.getDepartment().getId());
            di.setName(c.getDepartment().getName());
            di.setCode(c.getDepartment().getCode());
            r.setDepartment(di);
        }
        if (c.getAssignedHandler() != null) {
            AdminInfo ai = new AdminInfo();
            ai.setId(c.getAssignedHandler().getId());
            ai.setUsername(c.getAssignedHandler().getUsername());
            ai.setFullName(c.getAssignedHandler().getFullName());
            ai.setEmail(c.getAssignedHandler().getEmail());
            ai.setRole(c.getAssignedHandler().getRole().name());
            r.setAssignedHandler(ai);
        }
        // Calculate overdue/hours remaining
        if (c.getDueDate() != null && !isTerminal(c.getStatus())) {
            LocalDateTime now = LocalDateTime.now();
            long hours = java.time.Duration.between(now, c.getDueDate()).toHours();
            r.setHoursRemaining(hours);
            r.setOverdue(hours < 0);
        }
        return r;
    }

    private static boolean isTerminal(Complaint.Status status) {
        return status == Complaint.Status.CLOSED || status == Complaint.Status.REJECTED;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ComplaintResponse() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getComplaintId() {
        return this.complaintId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public StudentInfo getStudent() {
        return this.student;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTitle() {
        return this.title;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCategory() {
        return this.category;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPriority() {
        return this.priority;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public DepartmentInfo getDepartment() {
        return this.department;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public AdminInfo getAssignedHandler() {
        return this.assignedHandler;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getDueDate() {
        return this.dueDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getResolvedAt() {
        return this.resolvedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getClosedAt() {
        return this.closedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getRejectionReason() {
        return this.rejectionReason;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getResolutionNote() {
        return this.resolutionNote;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean isOverdue() {
        return this.overdue;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getHoursRemaining() {
        return this.hoursRemaining;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setComplaintId(final String complaintId) {
        this.complaintId = complaintId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStudent(final StudentInfo student) {
        this.student = student;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTitle(final String title) {
        this.title = title;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDescription(final String description) {
        this.description = description;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCategory(final String category) {
        this.category = category;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPriority(final String priority) {
        this.priority = priority;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDepartment(final DepartmentInfo department) {
        this.department = department;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAssignedHandler(final AdminInfo assignedHandler) {
        this.assignedHandler = assignedHandler;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatus(final String status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUpdatedAt(final LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDueDate(final LocalDateTime dueDate) {
        this.dueDate = dueDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setResolvedAt(final LocalDateTime resolvedAt) {
        this.resolvedAt = resolvedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setClosedAt(final LocalDateTime closedAt) {
        this.closedAt = closedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setRejectionReason(final String rejectionReason) {
        this.rejectionReason = rejectionReason;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setResolutionNote(final String resolutionNote) {
        this.resolutionNote = resolutionNote;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setOverdue(final boolean overdue) {
        this.overdue = overdue;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setHoursRemaining(final Long hoursRemaining) {
        this.hoursRemaining = hoursRemaining;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ComplaintResponse)) return false;
        final ComplaintResponse other = (ComplaintResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.isOverdue() != other.isOverdue()) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$hoursRemaining = this.getHoursRemaining();
        final java.lang.Object other$hoursRemaining = other.getHoursRemaining();
        if (this$hoursRemaining == null ? other$hoursRemaining != null : !this$hoursRemaining.equals(other$hoursRemaining)) return false;
        final java.lang.Object this$complaintId = this.getComplaintId();
        final java.lang.Object other$complaintId = other.getComplaintId();
        if (this$complaintId == null ? other$complaintId != null : !this$complaintId.equals(other$complaintId)) return false;
        final java.lang.Object this$student = this.getStudent();
        final java.lang.Object other$student = other.getStudent();
        if (this$student == null ? other$student != null : !this$student.equals(other$student)) return false;
        final java.lang.Object this$title = this.getTitle();
        final java.lang.Object other$title = other.getTitle();
        if (this$title == null ? other$title != null : !this$title.equals(other$title)) return false;
        final java.lang.Object this$description = this.getDescription();
        final java.lang.Object other$description = other.getDescription();
        if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
        final java.lang.Object this$category = this.getCategory();
        final java.lang.Object other$category = other.getCategory();
        if (this$category == null ? other$category != null : !this$category.equals(other$category)) return false;
        final java.lang.Object this$priority = this.getPriority();
        final java.lang.Object other$priority = other.getPriority();
        if (this$priority == null ? other$priority != null : !this$priority.equals(other$priority)) return false;
        final java.lang.Object this$department = this.getDepartment();
        final java.lang.Object other$department = other.getDepartment();
        if (this$department == null ? other$department != null : !this$department.equals(other$department)) return false;
        final java.lang.Object this$assignedHandler = this.getAssignedHandler();
        final java.lang.Object other$assignedHandler = other.getAssignedHandler();
        if (this$assignedHandler == null ? other$assignedHandler != null : !this$assignedHandler.equals(other$assignedHandler)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        final java.lang.Object this$updatedAt = this.getUpdatedAt();
        final java.lang.Object other$updatedAt = other.getUpdatedAt();
        if (this$updatedAt == null ? other$updatedAt != null : !this$updatedAt.equals(other$updatedAt)) return false;
        final java.lang.Object this$dueDate = this.getDueDate();
        final java.lang.Object other$dueDate = other.getDueDate();
        if (this$dueDate == null ? other$dueDate != null : !this$dueDate.equals(other$dueDate)) return false;
        final java.lang.Object this$resolvedAt = this.getResolvedAt();
        final java.lang.Object other$resolvedAt = other.getResolvedAt();
        if (this$resolvedAt == null ? other$resolvedAt != null : !this$resolvedAt.equals(other$resolvedAt)) return false;
        final java.lang.Object this$closedAt = this.getClosedAt();
        final java.lang.Object other$closedAt = other.getClosedAt();
        if (this$closedAt == null ? other$closedAt != null : !this$closedAt.equals(other$closedAt)) return false;
        final java.lang.Object this$rejectionReason = this.getRejectionReason();
        final java.lang.Object other$rejectionReason = other.getRejectionReason();
        if (this$rejectionReason == null ? other$rejectionReason != null : !this$rejectionReason.equals(other$rejectionReason)) return false;
        final java.lang.Object this$resolutionNote = this.getResolutionNote();
        final java.lang.Object other$resolutionNote = other.getResolutionNote();
        if (this$resolutionNote == null ? other$resolutionNote != null : !this$resolutionNote.equals(other$resolutionNote)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ComplaintResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + (this.isOverdue() ? 79 : 97);
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $hoursRemaining = this.getHoursRemaining();
        result = result * PRIME + ($hoursRemaining == null ? 43 : $hoursRemaining.hashCode());
        final java.lang.Object $complaintId = this.getComplaintId();
        result = result * PRIME + ($complaintId == null ? 43 : $complaintId.hashCode());
        final java.lang.Object $student = this.getStudent();
        result = result * PRIME + ($student == null ? 43 : $student.hashCode());
        final java.lang.Object $title = this.getTitle();
        result = result * PRIME + ($title == null ? 43 : $title.hashCode());
        final java.lang.Object $description = this.getDescription();
        result = result * PRIME + ($description == null ? 43 : $description.hashCode());
        final java.lang.Object $category = this.getCategory();
        result = result * PRIME + ($category == null ? 43 : $category.hashCode());
        final java.lang.Object $priority = this.getPriority();
        result = result * PRIME + ($priority == null ? 43 : $priority.hashCode());
        final java.lang.Object $department = this.getDepartment();
        result = result * PRIME + ($department == null ? 43 : $department.hashCode());
        final java.lang.Object $assignedHandler = this.getAssignedHandler();
        result = result * PRIME + ($assignedHandler == null ? 43 : $assignedHandler.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        final java.lang.Object $updatedAt = this.getUpdatedAt();
        result = result * PRIME + ($updatedAt == null ? 43 : $updatedAt.hashCode());
        final java.lang.Object $dueDate = this.getDueDate();
        result = result * PRIME + ($dueDate == null ? 43 : $dueDate.hashCode());
        final java.lang.Object $resolvedAt = this.getResolvedAt();
        result = result * PRIME + ($resolvedAt == null ? 43 : $resolvedAt.hashCode());
        final java.lang.Object $closedAt = this.getClosedAt();
        result = result * PRIME + ($closedAt == null ? 43 : $closedAt.hashCode());
        final java.lang.Object $rejectionReason = this.getRejectionReason();
        result = result * PRIME + ($rejectionReason == null ? 43 : $rejectionReason.hashCode());
        final java.lang.Object $resolutionNote = this.getResolutionNote();
        result = result * PRIME + ($resolutionNote == null ? 43 : $resolutionNote.hashCode());
        return result;
    }

    public java.util.List<ComplaintAttachmentResponse> getAttachments() {
        return this.attachments;
    }

    public void setAttachments(java.util.List<ComplaintAttachmentResponse> attachments) {
        this.attachments = attachments != null ? attachments : new java.util.ArrayList<>();
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "ComplaintResponse(id=" + this.getId() + ", complaintId=" + this.getComplaintId() + ", student=" + this.getStudent() + ", title=" + this.getTitle() + ", description=" + this.getDescription() + ", category=" + this.getCategory() + ", priority=" + this.getPriority() + ", department=" + this.getDepartment() + ", assignedHandler=" + this.getAssignedHandler() + ", status=" + this.getStatus() + ", createdAt=" + this.getCreatedAt() + ", updatedAt=" + this.getUpdatedAt() + ", dueDate=" + this.getDueDate() + ", resolvedAt=" + this.getResolvedAt() + ", closedAt=" + this.getClosedAt() + ", rejectionReason=" + this.getRejectionReason() + ", resolutionNote=" + this.getResolutionNote() + ", overdue=" + this.isOverdue() + ", hoursRemaining=" + this.getHoursRemaining() + ", attachments=" + this.getAttachments() + ")";
    }
}
