// Generated by delombok at Sat Sep 26 12:28:47 IST 2026
package com.campus.complaint.dto.response;

import java.util.List;
import java.util.Map;

public class DashboardResponse {
    private long totalComplaints;
    private long newComplaints;
    private long validatingComplaints;
    private long assignedComplaints;
    private long inProgressComplaints;
    private long resolvedComplaints;
    private long closedComplaints;
    private long escalatedComplaints;
    private long rejectedComplaints;
    private long overdueComplaints;
    private Map<String, Long> byStatus;
    private Map<String, Long> byCategory;
    private Map<String, Long> byPriority;
    private Map<String, Long> byDepartment;
    private List<ComplaintResponse> recentComplaints;
    private List<ComplaintResponse> approachingSla;
    private List<ComplaintResponse> overdueList;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public long getTotalComplaints() {
        return this.totalComplaints;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public long getNewComplaints() {
        return this.newComplaints;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public long getValidatingComplaints() {
        return this.validatingComplaints;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public long getAssignedComplaints() {
        return this.assignedComplaints;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public long getInProgressComplaints() {
        return this.inProgressComplaints;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public long getResolvedComplaints() {
        return this.resolvedComplaints;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public long getClosedComplaints() {
        return this.closedComplaints;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public long getEscalatedComplaints() {
        return this.escalatedComplaints;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public long getRejectedComplaints() {
        return this.rejectedComplaints;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public long getOverdueComplaints() {
        return this.overdueComplaints;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Map<String, Long> getByStatus() {
        return this.byStatus;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Map<String, Long> getByCategory() {
        return this.byCategory;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Map<String, Long> getByPriority() {
        return this.byPriority;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Map<String, Long> getByDepartment() {
        return this.byDepartment;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<ComplaintResponse> getRecentComplaints() {
        return this.recentComplaints;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<ComplaintResponse> getApproachingSla() {
        return this.approachingSla;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<ComplaintResponse> getOverdueList() {
        return this.overdueList;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTotalComplaints(final long totalComplaints) {
        this.totalComplaints = totalComplaints;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNewComplaints(final long newComplaints) {
        this.newComplaints = newComplaints;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setValidatingComplaints(final long validatingComplaints) {
        this.validatingComplaints = validatingComplaints;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAssignedComplaints(final long assignedComplaints) {
        this.assignedComplaints = assignedComplaints;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setInProgressComplaints(final long inProgressComplaints) {
        this.inProgressComplaints = inProgressComplaints;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setResolvedComplaints(final long resolvedComplaints) {
        this.resolvedComplaints = resolvedComplaints;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setClosedComplaints(final long closedComplaints) {
        this.closedComplaints = closedComplaints;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEscalatedComplaints(final long escalatedComplaints) {
        this.escalatedComplaints = escalatedComplaints;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setRejectedComplaints(final long rejectedComplaints) {
        this.rejectedComplaints = rejectedComplaints;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setOverdueComplaints(final long overdueComplaints) {
        this.overdueComplaints = overdueComplaints;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setByStatus(final Map<String, Long> byStatus) {
        this.byStatus = byStatus;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setByCategory(final Map<String, Long> byCategory) {
        this.byCategory = byCategory;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setByPriority(final Map<String, Long> byPriority) {
        this.byPriority = byPriority;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setByDepartment(final Map<String, Long> byDepartment) {
        this.byDepartment = byDepartment;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setRecentComplaints(final List<ComplaintResponse> recentComplaints) {
        this.recentComplaints = recentComplaints;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setApproachingSla(final List<ComplaintResponse> approachingSla) {
        this.approachingSla = approachingSla;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setOverdueList(final List<ComplaintResponse> overdueList) {
        this.overdueList = overdueList;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof DashboardResponse)) return false;
        final DashboardResponse other = (DashboardResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.getTotalComplaints() != other.getTotalComplaints()) return false;
        if (this.getNewComplaints() != other.getNewComplaints()) return false;
        if (this.getValidatingComplaints() != other.getValidatingComplaints()) return false;
        if (this.getAssignedComplaints() != other.getAssignedComplaints()) return false;
        if (this.getInProgressComplaints() != other.getInProgressComplaints()) return false;
        if (this.getResolvedComplaints() != other.getResolvedComplaints()) return false;
        if (this.getClosedComplaints() != other.getClosedComplaints()) return false;
        if (this.getEscalatedComplaints() != other.getEscalatedComplaints()) return false;
        if (this.getRejectedComplaints() != other.getRejectedComplaints()) return false;
        if (this.getOverdueComplaints() != other.getOverdueComplaints()) return false;
        final java.lang.Object this$byStatus = this.getByStatus();
        final java.lang.Object other$byStatus = other.getByStatus();
        if (this$byStatus == null ? other$byStatus != null : !this$byStatus.equals(other$byStatus)) return false;
        final java.lang.Object this$byCategory = this.getByCategory();
        final java.lang.Object other$byCategory = other.getByCategory();
        if (this$byCategory == null ? other$byCategory != null : !this$byCategory.equals(other$byCategory)) return false;
        final java.lang.Object this$byPriority = this.getByPriority();
        final java.lang.Object other$byPriority = other.getByPriority();
        if (this$byPriority == null ? other$byPriority != null : !this$byPriority.equals(other$byPriority)) return false;
        final java.lang.Object this$byDepartment = this.getByDepartment();
        final java.lang.Object other$byDepartment = other.getByDepartment();
        if (this$byDepartment == null ? other$byDepartment != null : !this$byDepartment.equals(other$byDepartment)) return false;
        final java.lang.Object this$recentComplaints = this.getRecentComplaints();
        final java.lang.Object other$recentComplaints = other.getRecentComplaints();
        if (this$recentComplaints == null ? other$recentComplaints != null : !this$recentComplaints.equals(other$recentComplaints)) return false;
        final java.lang.Object this$approachingSla = this.getApproachingSla();
        final java.lang.Object other$approachingSla = other.getApproachingSla();
        if (this$approachingSla == null ? other$approachingSla != null : !this$approachingSla.equals(other$approachingSla)) return false;
        final java.lang.Object this$overdueList = this.getOverdueList();
        final java.lang.Object other$overdueList = other.getOverdueList();
        if (this$overdueList == null ? other$overdueList != null : !this$overdueList.equals(other$overdueList)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof DashboardResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final long $totalComplaints = this.getTotalComplaints();
        result = result * PRIME + (int) ($totalComplaints >>> 32 ^ $totalComplaints);
        final long $newComplaints = this.getNewComplaints();
        result = result * PRIME + (int) ($newComplaints >>> 32 ^ $newComplaints);
        final long $validatingComplaints = this.getValidatingComplaints();
        result = result * PRIME + (int) ($validatingComplaints >>> 32 ^ $validatingComplaints);
        final long $assignedComplaints = this.getAssignedComplaints();
        result = result * PRIME + (int) ($assignedComplaints >>> 32 ^ $assignedComplaints);
        final long $inProgressComplaints = this.getInProgressComplaints();
        result = result * PRIME + (int) ($inProgressComplaints >>> 32 ^ $inProgressComplaints);
        final long $resolvedComplaints = this.getResolvedComplaints();
        result = result * PRIME + (int) ($resolvedComplaints >>> 32 ^ $resolvedComplaints);
        final long $closedComplaints = this.getClosedComplaints();
        result = result * PRIME + (int) ($closedComplaints >>> 32 ^ $closedComplaints);
        final long $escalatedComplaints = this.getEscalatedComplaints();
        result = result * PRIME + (int) ($escalatedComplaints >>> 32 ^ $escalatedComplaints);
        final long $rejectedComplaints = this.getRejectedComplaints();
        result = result * PRIME + (int) ($rejectedComplaints >>> 32 ^ $rejectedComplaints);
        final long $overdueComplaints = this.getOverdueComplaints();
        result = result * PRIME + (int) ($overdueComplaints >>> 32 ^ $overdueComplaints);
        final java.lang.Object $byStatus = this.getByStatus();
        result = result * PRIME + ($byStatus == null ? 43 : $byStatus.hashCode());
        final java.lang.Object $byCategory = this.getByCategory();
        result = result * PRIME + ($byCategory == null ? 43 : $byCategory.hashCode());
        final java.lang.Object $byPriority = this.getByPriority();
        result = result * PRIME + ($byPriority == null ? 43 : $byPriority.hashCode());
        final java.lang.Object $byDepartment = this.getByDepartment();
        result = result * PRIME + ($byDepartment == null ? 43 : $byDepartment.hashCode());
        final java.lang.Object $recentComplaints = this.getRecentComplaints();
        result = result * PRIME + ($recentComplaints == null ? 43 : $recentComplaints.hashCode());
        final java.lang.Object $approachingSla = this.getApproachingSla();
        result = result * PRIME + ($approachingSla == null ? 43 : $approachingSla.hashCode());
        final java.lang.Object $overdueList = this.getOverdueList();
        result = result * PRIME + ($overdueList == null ? 43 : $overdueList.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "DashboardResponse(totalComplaints=" + this.getTotalComplaints() + ", newComplaints=" + this.getNewComplaints() + ", validatingComplaints=" + this.getValidatingComplaints() + ", assignedComplaints=" + this.getAssignedComplaints() + ", inProgressComplaints=" + this.getInProgressComplaints() + ", resolvedComplaints=" + this.getResolvedComplaints() + ", closedComplaints=" + this.getClosedComplaints() + ", escalatedComplaints=" + this.getEscalatedComplaints() + ", rejectedComplaints=" + this.getRejectedComplaints() + ", overdueComplaints=" + this.getOverdueComplaints() + ", byStatus=" + this.getByStatus() + ", byCategory=" + this.getByCategory() + ", byPriority=" + this.getByPriority() + ", byDepartment=" + this.getByDepartment() + ", recentComplaints=" + this.getRecentComplaints() + ", approachingSla=" + this.getApproachingSla() + ", overdueList=" + this.getOverdueList() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public DashboardResponse() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public DashboardResponse(final long totalComplaints, final long newComplaints, final long validatingComplaints, final long assignedComplaints, final long inProgressComplaints, final long resolvedComplaints, final long closedComplaints, final long escalatedComplaints, final long rejectedComplaints, final long overdueComplaints, final Map<String, Long> byStatus, final Map<String, Long> byCategory, final Map<String, Long> byPriority, final Map<String, Long> byDepartment, final List<ComplaintResponse> recentComplaints, final List<ComplaintResponse> approachingSla, final List<ComplaintResponse> overdueList) {
        this.totalComplaints = totalComplaints;
        this.newComplaints = newComplaints;
        this.validatingComplaints = validatingComplaints;
        this.assignedComplaints = assignedComplaints;
        this.inProgressComplaints = inProgressComplaints;
        this.resolvedComplaints = resolvedComplaints;
        this.closedComplaints = closedComplaints;
        this.escalatedComplaints = escalatedComplaints;
        this.rejectedComplaints = rejectedComplaints;
        this.overdueComplaints = overdueComplaints;
        this.byStatus = byStatus;
        this.byCategory = byCategory;
        this.byPriority = byPriority;
        this.byDepartment = byDepartment;
        this.recentComplaints = recentComplaints;
        this.approachingSla = approachingSla;
        this.overdueList = overdueList;
    }
}
