// Generated by delombok at Sat Sep 26 12:28:47 IST 2026
package com.campus.complaint.dto.request;

import jakarta.validation.constraints.NotBlank;

public class AddCommentRequest {
    @NotBlank(message = "Content is required")
    private String content;
    private boolean internal = false;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public AddCommentRequest() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getContent() {
        return this.content;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean isInternal() {
        return this.internal;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setContent(final String content) {
        this.content = content;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setInternal(final boolean internal) {
        this.internal = internal;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof AddCommentRequest)) return false;
        final AddCommentRequest other = (AddCommentRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.isInternal() != other.isInternal()) return false;
        final java.lang.Object this$content = this.getContent();
        final java.lang.Object other$content = other.getContent();
        if (this$content == null ? other$content != null : !this$content.equals(other$content)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof AddCommentRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + (this.isInternal() ? 79 : 97);
        final java.lang.Object $content = this.getContent();
        result = result * PRIME + ($content == null ? 43 : $content.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "AddCommentRequest(content=" + this.getContent() + ", internal=" + this.isInternal() + ")";
    }
}
