// Generated by delombok at Sat Sep 26 12:28:47 IST 2026
package com.campus.complaint.dto.request;

import jakarta.validation.constraints.NotNull;

public class AssignComplaintRequest {
    @NotNull(message = "Handler ID is required")
    private Long handlerId;
    private String note;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public AssignComplaintRequest() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getHandlerId() {
        return this.handlerId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNote() {
        return this.note;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setHandlerId(final Long handlerId) {
        this.handlerId = handlerId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNote(final String note) {
        this.note = note;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof AssignComplaintRequest)) return false;
        final AssignComplaintRequest other = (AssignComplaintRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$handlerId = this.getHandlerId();
        final java.lang.Object other$handlerId = other.getHandlerId();
        if (this$handlerId == null ? other$handlerId != null : !this$handlerId.equals(other$handlerId)) return false;
        final java.lang.Object this$note = this.getNote();
        final java.lang.Object other$note = other.getNote();
        if (this$note == null ? other$note != null : !this$note.equals(other$note)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof AssignComplaintRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $handlerId = this.getHandlerId();
        result = result * PRIME + ($handlerId == null ? 43 : $handlerId.hashCode());
        final java.lang.Object $note = this.getNote();
        result = result * PRIME + ($note == null ? 43 : $note.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "AssignComplaintRequest(handlerId=" + this.getHandlerId() + ", note=" + this.getNote() + ")";
    }
}
