// Generated by delombok at Sat Sep 26 12:28:47 IST 2026
package com.campus.complaint.dto.request;

import com.campus.complaint.entity.Complaint;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

public class CreateComplaintRequest {
    @NotNull(message = "Student ID is required")
    private Long studentId;
    @NotBlank(message = "Title is required")
    private String title;
    @NotBlank(message = "Description is required")
    private String description;
    @NotNull(message = "Category is required")
    private Complaint.Category category;
    @NotNull(message = "Priority is required")
    private Complaint.Priority priority;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public CreateComplaintRequest() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getStudentId() {
        return this.studentId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTitle() {
        return this.title;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Complaint.Category getCategory() {
        return this.category;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Complaint.Priority getPriority() {
        return this.priority;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStudentId(final Long studentId) {
        this.studentId = studentId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTitle(final String title) {
        this.title = title;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDescription(final String description) {
        this.description = description;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCategory(final Complaint.Category category) {
        this.category = category;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPriority(final Complaint.Priority priority) {
        this.priority = priority;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof CreateComplaintRequest)) return false;
        final CreateComplaintRequest other = (CreateComplaintRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$studentId = this.getStudentId();
        final java.lang.Object other$studentId = other.getStudentId();
        if (this$studentId == null ? other$studentId != null : !this$studentId.equals(other$studentId)) return false;
        final java.lang.Object this$title = this.getTitle();
        final java.lang.Object other$title = other.getTitle();
        if (this$title == null ? other$title != null : !this$title.equals(other$title)) return false;
        final java.lang.Object this$description = this.getDescription();
        final java.lang.Object other$description = other.getDescription();
        if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
        final java.lang.Object this$category = this.getCategory();
        final java.lang.Object other$category = other.getCategory();
        if (this$category == null ? other$category != null : !this$category.equals(other$category)) return false;
        final java.lang.Object this$priority = this.getPriority();
        final java.lang.Object other$priority = other.getPriority();
        if (this$priority == null ? other$priority != null : !this$priority.equals(other$priority)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof CreateComplaintRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $studentId = this.getStudentId();
        result = result * PRIME + ($studentId == null ? 43 : $studentId.hashCode());
        final java.lang.Object $title = this.getTitle();
        result = result * PRIME + ($title == null ? 43 : $title.hashCode());
        final java.lang.Object $description = this.getDescription();
        result = result * PRIME + ($description == null ? 43 : $description.hashCode());
        final java.lang.Object $category = this.getCategory();
        result = result * PRIME + ($category == null ? 43 : $category.hashCode());
        final java.lang.Object $priority = this.getPriority();
        result = result * PRIME + ($priority == null ? 43 : $priority.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "CreateComplaintRequest(studentId=" + this.getStudentId() + ", title=" + this.getTitle() + ", description=" + this.getDescription() + ", category=" + this.getCategory() + ", priority=" + this.getPriority() + ")";
    }
}
