// Generated by delombok at Sat Sep 26 12:28:47 IST 2026
package com.campus.complaint.dto.request;

import jakarta.validation.constraints.NotBlank;

public class EscalateRequest {
    @NotBlank(message = "Reason is required")
    private String reason;
    private Long newAssigneeId;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public EscalateRequest() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getReason() {
        return this.reason;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getNewAssigneeId() {
        return this.newAssigneeId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setReason(final String reason) {
        this.reason = reason;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNewAssigneeId(final Long newAssigneeId) {
        this.newAssigneeId = newAssigneeId;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof EscalateRequest)) return false;
        final EscalateRequest other = (EscalateRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$newAssigneeId = this.getNewAssigneeId();
        final java.lang.Object other$newAssigneeId = other.getNewAssigneeId();
        if (this$newAssigneeId == null ? other$newAssigneeId != null : !this$newAssigneeId.equals(other$newAssigneeId)) return false;
        final java.lang.Object this$reason = this.getReason();
        final java.lang.Object other$reason = other.getReason();
        if (this$reason == null ? other$reason != null : !this$reason.equals(other$reason)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof EscalateRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $newAssigneeId = this.getNewAssigneeId();
        result = result * PRIME + ($newAssigneeId == null ? 43 : $newAssigneeId.hashCode());
        final java.lang.Object $reason = this.getReason();
        result = result * PRIME + ($reason == null ? 43 : $reason.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "EscalateRequest(reason=" + this.getReason() + ", newAssigneeId=" + this.getNewAssigneeId() + ")";
    }
}
