// Generated by delombok at Sat Sep 26 12:28:47 IST 2026
package com.campus.complaint.service;

import com.campus.complaint.dto.request.CreateAdminRequest;
import com.campus.complaint.entity.Admin;
import com.campus.complaint.entity.Department;
import com.campus.complaint.exception.BusinessException;
import com.campus.complaint.exception.ResourceNotFoundException;
import com.campus.complaint.repository.AdminRepository;
import com.campus.complaint.repository.DepartmentRepository;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.util.List;

@Service
public class AdminService {
    private final AdminRepository adminRepository;
    private final DepartmentRepository departmentRepository;
    private final PasswordEncoder passwordEncoder;
    private final AuditLogService auditLogService;

    public List<Admin> getAllAdmins() {
        return adminRepository.findAll();
    }

    public Admin getById(Long id) {
        return adminRepository.findById(id).orElseThrow(() -> new ResourceNotFoundException("Admin", id));
    }

    @Transactional
    public Admin createAdmin(CreateAdminRequest req, Admin actor) {
        if (adminRepository.existsByUsername(req.getUsername())) {
            throw new BusinessException("Username already exists: " + req.getUsername());
        }
        if (adminRepository.existsByEmail(req.getEmail())) {
            throw new BusinessException("Email already exists: " + req.getEmail());
        }
        Admin admin = new Admin();
        admin.setUsername(req.getUsername());
        admin.setEmail(req.getEmail());
        admin.setPassword(passwordEncoder.encode(req.getPassword()));
        admin.setFullName(req.getFullName());
        admin.setRole(req.getRole());
        if (req.getDepartmentId() != null) {
            Department dept = departmentRepository.findById(req.getDepartmentId()).orElseThrow(() -> new ResourceNotFoundException("Department", req.getDepartmentId()));
            admin.setDepartment(dept);
        }
        Admin saved = adminRepository.save(admin);
        auditLogService.log(actor, "ADMIN_CREATED", "Admin created: " + saved.getUsername());
        return saved;
    }

    @Transactional
    public Admin toggleActive(Long id, Admin actor) {
        Admin admin = getById(id);
        admin.setActive(!admin.isActive());
        Admin saved = adminRepository.save(admin);
        auditLogService.log(actor, "ADMIN_STATUS_CHANGED", "Admin " + admin.getUsername() + " active: " + admin.isActive());
        return saved;
    }

    @Transactional
    public void deleteAdmin(Long id, Admin actor) {
        Admin admin = getById(id);
        auditLogService.log(actor, "ADMIN_DELETED", "Admin deleted: " + admin.getUsername());
        adminRepository.delete(admin);
    }

    public List<Admin> getHandlers() {
        return adminRepository.findByRole(Admin.Role.COMPLAINT_HANDLER);
    }

    public List<Department> getAllDepartments() {
        return departmentRepository.findAll();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public AdminService(final AdminRepository adminRepository, final DepartmentRepository departmentRepository, final PasswordEncoder passwordEncoder, final AuditLogService auditLogService) {
        this.adminRepository = adminRepository;
        this.departmentRepository = departmentRepository;
        this.passwordEncoder = passwordEncoder;
        this.auditLogService = auditLogService;
    }
}
