// Generated by delombok at Sat Sep 26 12:28:47 IST 2026
package com.campus.complaint.service;

import com.campus.complaint.entity.Admin;
import com.campus.complaint.entity.AuditLog;
import com.campus.complaint.entity.Complaint;
import com.campus.complaint.repository.AuditLogRepository;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.util.List;

@Service
public class AuditLogService {
    private final AuditLogRepository auditLogRepository;

    @Transactional
    public void log(Admin admin, Complaint complaint, String action, String entityType, String oldValue, String newValue, String description) {
        AuditLog log = new AuditLog();
        log.setAdmin(admin);
        log.setComplaint(complaint);
        log.setAction(action);
        log.setEntityType(entityType);
        log.setOldValue(oldValue);
        log.setNewValue(newValue);
        log.setDescription(description);
        auditLogRepository.save(log);
    }

    @Transactional
    public void log(Admin admin, String action, String description) {
        log(admin, null, action, "SYSTEM", null, null, description);
    }

    public Page<AuditLog> getAll(Pageable pageable) {
        return auditLogRepository.findAllByOrderByCreatedAtDesc(pageable);
    }

    public List<AuditLog> getByComplaint(Long complaintId) {
        return auditLogRepository.findByComplaintIdOrderByCreatedAtAsc(complaintId);
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public AuditLogService(final AuditLogRepository auditLogRepository) {
        this.auditLogRepository = auditLogRepository;
    }
}
