// Generated by delombok at Sat Sep 26 12:28:47 IST 2026
package com.campus.complaint.service;

import com.campus.complaint.dto.request.*;
import com.campus.complaint.dto.response.ComplaintResponse;
import com.campus.complaint.dto.response.DashboardResponse;
import com.campus.complaint.entity.*;
import com.campus.complaint.exception.BusinessException;
import com.campus.complaint.exception.ResourceNotFoundException;
import com.campus.complaint.repository.*;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.LocalDateTime;
import java.util.*;
import java.util.stream.Collectors;

@Service
public class ComplaintService {
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(ComplaintService.class);
    private final ComplaintRepository complaintRepository;
    private final StudentRepository studentRepository;
    private final AdminRepository adminRepository;
    private final DepartmentRepository departmentRepository;
    private final CommentRepository commentRepository;
    private final EscalationRepository escalationRepository;
    private final AuditLogService auditLogService;
    private final NotificationService notificationService;
    private final com.campus.complaint.repository.ComplaintAttachmentRepository attachmentRepository;

    // =============================================
    // COMPLAINT ID GENERATION
    // =============================================
    @Transactional
    public synchronized String generateComplaintId() {
        Optional<Long> maxId = complaintRepository.findMaxId();
        long nextNum = maxId.map(id -> id + 1).orElse(1L);
        return String.format("CMP-%04d", nextNum);
    }

    // =============================================
    // AUTO-ROUTING
    // =============================================
    private Department routeToDepartment(Complaint.Category category) {
        String code = switch (category) {
            case IT -> "IT";
            case HOSTEL -> "HOSTEL";
            case TRANSPORT -> "TRANSPORT";
            case INFRASTRUCTURE, MAINTENANCE -> "FACILITIES";
            case ACADEMIC -> "ACADEMIC";
            case SAFETY -> "SAFETY";
            default -> "GENERAL";
        };
        return departmentRepository.findByCode(code).orElse(null);
    }

    // =============================================
    // CREATE COMPLAINT
    // =============================================
    @Transactional
    public ComplaintResponse createComplaint(CreateComplaintRequest req, Admin actor) {
        Student student = studentRepository.findById(req.getStudentId()).orElseThrow(() -> new ResourceNotFoundException("Student", req.getStudentId()));
        Complaint c = new Complaint();
        c.setComplaintId(generateComplaintId());
        c.setStudent(student);
        c.setTitle(req.getTitle());
        c.setDescription(req.getDescription());
        c.setCategory(req.getCategory());
        c.setPriority(req.getPriority());
        c.setStatus(Complaint.Status.NEW);
        c.setDepartment(routeToDepartment(req.getCategory()));
        c.setDueDate(LocalDateTime.now().plusHours(req.getPriority().getSlaHours()));
        Complaint saved = complaintRepository.save(c);
        auditLogService.log(actor, saved, "COMPLAINT_CREATED", "COMPLAINT", null, saved.getComplaintId(), "Complaint created: " + saved.getTitle());
        return ComplaintResponse.from(saved);
    }

    // =============================================
    // GET ALL COMPLAINTS (with filters)
    // =============================================
    public Page<ComplaintResponse> getAllComplaints(String status, String category, String priority, Long departmentId, String search, Admin actor, Pageable pageable) {
        Specification<Complaint> spec = buildSpec(status, category, priority, departmentId, search, actor);
        Page<Complaint> page = complaintRepository.findAll(spec, pageable);
        List<ComplaintResponse> content = page.getContent().stream().map(ComplaintResponse::from).collect(Collectors.toList());
        return new PageImpl<>(content, pageable, page.getTotalElements());
    }

    private Specification<Complaint> buildSpec(String status, String category, String priority, Long departmentId, String search, Admin actor) {
        return (root, query, cb) -> {
            List<jakarta.persistence.criteria.Predicate> predicates = new ArrayList<>();
            // Role-based filtering
            if (actor.getRole() == Admin.Role.COMPLAINT_HANDLER) {
                predicates.add(cb.equal(root.get("assignedHandler").get("id"), actor.getId()));
            } else if (actor.getRole() == Admin.Role.DEPARTMENT_ADMIN && actor.getDepartment() != null) {
                predicates.add(cb.equal(root.get("department").get("id"), actor.getDepartment().getId()));
            }
            if (status != null && !status.isBlank()) {
                predicates.add(cb.equal(root.get("status"), Complaint.Status.valueOf(status)));
            }
            if (category != null && !category.isBlank()) {
                predicates.add(cb.equal(root.get("category"), Complaint.Category.valueOf(category)));
            }
            if (priority != null && !priority.isBlank()) {
                predicates.add(cb.equal(root.get("priority"), Complaint.Priority.valueOf(priority)));
            }
            if (departmentId != null) {
                predicates.add(cb.equal(root.get("department").get("id"), departmentId));
            }
            if (search != null && !search.isBlank()) {
                String like = "%" + search.toLowerCase() + "%";
                predicates.add(cb.or(cb.like(cb.lower(root.get("title")), like), cb.like(cb.lower(root.get("complaintId")), like), cb.like(cb.lower(root.get("description")), like)));
            }
            query.orderBy(cb.desc(root.get("createdAt")));
            return cb.and(predicates.toArray(new jakarta.persistence.criteria.Predicate[0]));
        };
    }

    // =============================================
    // GET BY ID
    // =============================================
    public ComplaintResponse getById(String complaintId) {
        Complaint c = complaintRepository.findByComplaintId(complaintId)
                .or(() -> {
                    try {
                        return complaintRepository.findById(Long.parseLong(complaintId));
                    } catch (Exception e) {
                        return Optional.empty();
                    }
                })
                .orElseThrow(() -> new ResourceNotFoundException("Complaint not found: " + complaintId));
        ComplaintResponse resp = ComplaintResponse.from(c);
        if (attachmentRepository != null) {
            List<com.campus.complaint.entity.ComplaintAttachment> atts = attachmentRepository.findByComplaintIdOrderByCreatedAtAsc(c.getId());
            resp.setAttachments(atts.stream().map(com.campus.complaint.dto.response.ComplaintAttachmentResponse::from).collect(Collectors.toList()));
        }
        return resp;
    }

    // =============================================
    // ASSIGN HANDLER
    // =============================================
    @Transactional
    public ComplaintResponse assignHandler(String complaintId, AssignComplaintRequest req, Admin actor) {
        Complaint c = findByComplaintId(complaintId);
        if (c.getStatus() == Complaint.Status.CLOSED || c.getStatus() == Complaint.Status.REJECTED) {
            throw new BusinessException("Cannot assign handler to a closed or rejected complaint");
        }
        Admin handler = adminRepository.findById(req.getHandlerId()).orElseThrow(() -> new ResourceNotFoundException("Admin", req.getHandlerId()));
        if (handler.getRole() != Admin.Role.COMPLAINT_HANDLER) {
            throw new BusinessException("Assignee must have COMPLAINT_HANDLER role");
        }
        Admin previousHandler = c.getAssignedHandler();
        c.setAssignedHandler(handler);
        Complaint.Status newStatus = (c.getStatus() == Complaint.Status.NEW || c.getStatus() == Complaint.Status.VALIDATING) ? Complaint.Status.ASSIGNED : c.getStatus();
        c.setStatus(newStatus);
        Complaint saved = complaintRepository.save(c);
        auditLogService.log(actor, saved, "COMPLAINT_ASSIGNED", "COMPLAINT", previousHandler != null ? previousHandler.getFullName() : "Unassigned", handler.getFullName(), "Assigned to: " + handler.getFullName());
        notificationService.send(handler, saved, "New Assignment: " + saved.getComplaintId(), "Complaint " + saved.getComplaintId() + " has been assigned to you.", Notification.Type.ASSIGNMENT);
        return ComplaintResponse.from(saved);
    }

    // =============================================
    // UPDATE STATUS
    // =============================================
    @Transactional
    public ComplaintResponse updateStatus(String complaintId, UpdateStatusRequest req, Admin actor) {
        Complaint c = findByComplaintId(complaintId);
        Complaint.Status oldStatus = c.getStatus();
        Complaint.Status newStatus = req.getStatus();
        if (!oldStatus.canTransitionTo(newStatus)) {
            throw new BusinessException("Invalid status transition: " + oldStatus + " → " + newStatus);
        }
        c.setStatus(newStatus);
        if (newStatus == Complaint.Status.RESOLVED) {
            c.setResolvedAt(LocalDateTime.now());
            c.setResolutionNote(req.getReason());
        } else if (newStatus == Complaint.Status.CLOSED) {
            c.setClosedAt(LocalDateTime.now());
        } else if (newStatus == Complaint.Status.REJECTED) {
            c.setRejectionReason(req.getReason());
        }
        Complaint saved = complaintRepository.save(c);
        auditLogService.log(actor, saved, "STATUS_CHANGED", "COMPLAINT", oldStatus.name(), newStatus.name(), "Status changed: " + oldStatus + " → " + newStatus);
        // Notify handler
        if (saved.getAssignedHandler() != null) {
            notificationService.send(saved.getAssignedHandler(), saved, "Status Update: " + saved.getComplaintId(), "Status changed to " + newStatus, Notification.Type.STATUS_CHANGE);
        }
        return ComplaintResponse.from(saved);
    }

    // =============================================
    // UPDATE PRIORITY
    // =============================================
    @Transactional
    public ComplaintResponse updatePriority(String complaintId, Complaint.Priority newPriority, Admin actor) {
        Complaint c = findByComplaintId(complaintId);
        if (c.getStatus() == Complaint.Status.CLOSED || c.getStatus() == Complaint.Status.REJECTED) {
            throw new BusinessException("Cannot change priority of a closed complaint");
        }
        Complaint.Priority oldPriority = c.getPriority();
        c.setPriority(newPriority);
        // Recalculate SLA from creation date
        c.setDueDate(c.getCreatedAt().plusHours(newPriority.getSlaHours()));
        Complaint saved = complaintRepository.save(c);
        auditLogService.log(actor, saved, "PRIORITY_CHANGED", "COMPLAINT", oldPriority.name(), newPriority.name(), "Priority changed from " + oldPriority + " to " + newPriority);
        return ComplaintResponse.from(saved);
    }

    // =============================================
    // ADD COMMENT
    // =============================================
    @Transactional
    public Comment addComment(String complaintId, AddCommentRequest req, Admin actor) {
        Complaint c = findByComplaintId(complaintId);
        Comment comment = new Comment();
        comment.setComplaint(c);
        comment.setAdmin(actor);
        comment.setContent(req.getContent());
        comment.setInternal(req.isInternal());
        Comment saved = commentRepository.save(comment);
        auditLogService.log(actor, c, "COMMENT_ADDED", "COMMENT", null, req.getContent(), "Comment added");
        return saved;
    }

    public List<Comment> getComments(String complaintId) {
        Complaint c = findByComplaintId(complaintId);
        return commentRepository.findByComplaintIdOrderByCreatedAtAsc(c.getId());
    }

    // =============================================
    // ESCALATE
    // =============================================
    @Transactional
    public ComplaintResponse escalate(String complaintId, EscalateRequest req, Admin actor) {
        Complaint c = findByComplaintId(complaintId);
        if (c.getStatus() == Complaint.Status.CLOSED || c.getStatus() == Complaint.Status.REJECTED) {
            throw new BusinessException("Cannot escalate a closed or rejected complaint");
        }
        Escalation escalation = new Escalation();
        escalation.setComplaint(c);
        escalation.setEscalatedBy(actor);
        escalation.setReason(req.getReason());
        escalation.setPreviousAssignee(c.getAssignedHandler());
        if (req.getNewAssigneeId() != null) {
            Admin newAssignee = adminRepository.findById(req.getNewAssigneeId()).orElseThrow(() -> new ResourceNotFoundException("Admin", req.getNewAssigneeId()));
            escalation.setNewAssignee(newAssignee);
            c.setAssignedHandler(newAssignee);
            notificationService.send(newAssignee, c, "Escalated: " + c.getComplaintId(), "Complaint " + c.getComplaintId() + " has been escalated to you.", Notification.Type.ESCALATION);
        }
        escalationRepository.save(escalation);
        c.setStatus(Complaint.Status.ESCALATED);
        Complaint saved = complaintRepository.save(c);
        auditLogService.log(actor, saved, "COMPLAINT_ESCALATED", "ESCALATION", c.getStatus().name(), Complaint.Status.ESCALATED.name(), "Escalated: " + req.getReason());
        return ComplaintResponse.from(saved);
    }

    public List<Escalation> getEscalations(String complaintId) {
        Complaint c = findByComplaintId(complaintId);
        return escalationRepository.findByComplaintIdOrderByEscalatedAtDesc(c.getId());
    }

    // =============================================
    // RESOLVE
    // =============================================
    @Transactional
    public ComplaintResponse resolve(String complaintId, String resolutionNote, Admin actor) {
        Complaint c = findByComplaintId(complaintId);
        if (!c.getStatus().canTransitionTo(Complaint.Status.RESOLVED)) {
            throw new BusinessException("Cannot resolve complaint in status: " + c.getStatus());
        }
        c.setStatus(Complaint.Status.RESOLVED);
        c.setResolvedAt(LocalDateTime.now());
        c.setResolutionNote(resolutionNote);
        Complaint saved = complaintRepository.save(c);
        auditLogService.log(actor, saved, "COMPLAINT_RESOLVED", "COMPLAINT", "IN_PROGRESS", "RESOLVED", "Resolved: " + resolutionNote);
        // Notify
        notificationService.send(actor, saved, "Resolved: " + saved.getComplaintId(), "Complaint " + saved.getComplaintId() + " has been resolved.", Notification.Type.RESOLUTION);
        return ComplaintResponse.from(saved);
    }

    // =============================================
    // CLOSE
    // =============================================
    @Transactional
    public ComplaintResponse close(String complaintId, Admin actor) {
        Complaint c = findByComplaintId(complaintId);
        if (!c.getStatus().canTransitionTo(Complaint.Status.CLOSED)) {
            throw new BusinessException("Cannot close complaint in status: " + c.getStatus());
        }
        c.setStatus(Complaint.Status.CLOSED);
        c.setClosedAt(LocalDateTime.now());
        Complaint saved = complaintRepository.save(c);
        auditLogService.log(actor, saved, "COMPLAINT_CLOSED", "COMPLAINT", "STUDENT_VERIFICATION", "CLOSED", "Complaint closed");
        return ComplaintResponse.from(saved);
    }

    // =============================================
    // DASHBOARD
    // =============================================
    public DashboardResponse getDashboard(Admin actor) {
        DashboardResponse dashboard = new DashboardResponse();
        dashboard.setTotalComplaints(complaintRepository.count());
        dashboard.setNewComplaints(complaintRepository.countByStatus(Complaint.Status.NEW));
        dashboard.setValidatingComplaints(complaintRepository.countByStatus(Complaint.Status.VALIDATING));
        dashboard.setAssignedComplaints(complaintRepository.countByStatus(Complaint.Status.ASSIGNED));
        dashboard.setInProgressComplaints(complaintRepository.countByStatus(Complaint.Status.IN_PROGRESS));
        dashboard.setResolvedComplaints(complaintRepository.countByStatus(Complaint.Status.RESOLVED));
        dashboard.setClosedComplaints(complaintRepository.countByStatus(Complaint.Status.CLOSED));
        dashboard.setEscalatedComplaints(complaintRepository.countByStatus(Complaint.Status.ESCALATED));
        LocalDateTime now = LocalDateTime.now();
        List<Complaint> overdue = complaintRepository.findOverdueComplaints(now);
        dashboard.setOverdueComplaints(overdue.size());
        // Group by maps
        Map<String, Long> byStatus = new LinkedHashMap<>();
        complaintRepository.countByStatusGrouped().forEach(row -> byStatus.put((String) row[0].toString(), (Long) row[1]));
        dashboard.setByStatus(byStatus);
        Map<String, Long> byCategory = new LinkedHashMap<>();
        complaintRepository.countByCategoryGrouped().forEach(row -> byCategory.put((String) row[0].toString(), (Long) row[1]));
        dashboard.setByCategory(byCategory);
        Map<String, Long> byPriority = new LinkedHashMap<>();
        complaintRepository.countByPriorityGrouped().forEach(row -> byPriority.put((String) row[0].toString(), (Long) row[1]));
        dashboard.setByPriority(byPriority);
        Map<String, Long> byDept = new LinkedHashMap<>();
        complaintRepository.countByDepartmentGrouped().forEach(row -> byDept.put((String) row[0], (Long) row[1]));
        dashboard.setByDepartment(byDept);
        // Recent
        Pageable recentPage = org.springframework.data.domain.PageRequest.of(0, 10);
        List<ComplaintResponse> recent = complaintRepository.findRecentComplaints(recentPage).stream().map(ComplaintResponse::from).collect(Collectors.toList());
        dashboard.setRecentComplaints(recent);
        // Approaching SLA
        LocalDateTime slaThreshold = now.plusHours(4);
        List<ComplaintResponse> approaching = complaintRepository.findApproachingSla(now, slaThreshold).stream().map(ComplaintResponse::from).collect(Collectors.toList());
        dashboard.setApproachingSla(approaching);
        // Overdue list
        List<ComplaintResponse> overdueList = overdue.stream().map(ComplaintResponse::from).collect(Collectors.toList());
        dashboard.setOverdueList(overdueList);
        return dashboard;
    }

    // =============================================
    // REPORTS
    // =============================================
    public Map<String, Object> getReports() {
        Map<String, Object> report = new LinkedHashMap<>();
        Map<String, Long> byCategory = new LinkedHashMap<>();
        complaintRepository.countByCategoryGrouped().forEach(row -> byCategory.put(row[0].toString(), (Long) row[1]));
        Map<String, Long> byDept = new LinkedHashMap<>();
        complaintRepository.countByDepartmentGrouped().forEach(row -> byDept.put((String) row[0], (Long) row[1]));
        Map<String, Long> byStatus = new LinkedHashMap<>();
        complaintRepository.countByStatusGrouped().forEach(row -> byStatus.put(row[0].toString(), (Long) row[1]));
        Map<String, Long> byPriority = new LinkedHashMap<>();
        complaintRepository.countByPriorityGrouped().forEach(row -> byPriority.put(row[0].toString(), (Long) row[1]));
        LocalDateTime now = LocalDateTime.now();
        long overdueCount = complaintRepository.findOverdueComplaints(now).size();
        long escalatedCount = escalationRepository.countByResolvedFalse();
        Double avgResolution = complaintRepository.findAverageResolutionTimeHours();
        report.put("byCategory", byCategory);
        report.put("byDepartment", byDept);
        report.put("byStatus", byStatus);
        report.put("byPriority", byPriority);
        report.put("overdueCount", overdueCount);
        report.put("escalatedCount", escalatedCount);
        report.put("averageResolutionHours", avgResolution != null ? Math.round(avgResolution) : 0);
        report.put("totalComplaints", complaintRepository.count());
        return report;
    }

    // =============================================
    // SLA CHECKER (runs every hour)
    // =============================================
    @Scheduled(fixedRate = 3600000)
    @Transactional
    public void checkSlaBreaches() {
        LocalDateTime now = LocalDateTime.now();
        LocalDateTime warnThreshold = now.plusHours(4);
        List<Complaint> approaching = complaintRepository.findApproachingSla(now, warnThreshold);
        for (Complaint c : approaching) {
            if (c.getAssignedHandler() != null) {
                notificationService.send(c.getAssignedHandler(), c, "SLA Warning: " + c.getComplaintId(), "Complaint " + c.getComplaintId() + " is approaching its SLA deadline.", Notification.Type.SLA_WARNING);
            }
        }
        log.info("SLA check: {} approaching SLA", approaching.size());
    }

    // =============================================
    // STUDENTS
    // =============================================
    public List<Student> getAllStudents() {
        return studentRepository.findAll();
    }

    public List<Admin> getHandlers() {
        return adminRepository.findByRole(Admin.Role.COMPLAINT_HANDLER);
    }

    // Helpers
    private Complaint findByComplaintId(String complaintId) {
        return complaintRepository.findByComplaintId(complaintId).orElseThrow(() -> new ResourceNotFoundException("Complaint not found: " + complaintId));
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ComplaintService(final ComplaintRepository complaintRepository, final StudentRepository studentRepository, final AdminRepository adminRepository, final DepartmentRepository departmentRepository, final CommentRepository commentRepository, final EscalationRepository escalationRepository, final AuditLogService auditLogService, final NotificationService notificationService, final com.campus.complaint.repository.ComplaintAttachmentRepository attachmentRepository) {
        this.complaintRepository = complaintRepository;
        this.studentRepository = studentRepository;
        this.adminRepository = adminRepository;
        this.departmentRepository = departmentRepository;
        this.commentRepository = commentRepository;
        this.escalationRepository = escalationRepository;
        this.auditLogService = auditLogService;
        this.notificationService = notificationService;
        this.attachmentRepository = attachmentRepository;
    }
}
