// Generated by delombok at Sat Sep 26 12:28:47 IST 2026
package com.campus.complaint.service;

import com.campus.complaint.entity.Admin;
import com.campus.complaint.entity.Complaint;
import com.campus.complaint.entity.Notification;
import com.campus.complaint.repository.NotificationRepository;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.util.List;

@Service
public class NotificationService {
    private final NotificationRepository notificationRepository;

    @Transactional
    public void send(Admin admin, Complaint complaint, String title, String message, Notification.Type type) {
        Notification n = new Notification();
        n.setAdmin(admin);
        n.setComplaint(complaint);
        n.setTitle(title);
        n.setMessage(message);
        n.setType(type);
        notificationRepository.save(n);
    }

    public List<Notification> getForAdmin(Long adminId) {
        return notificationRepository.findByAdminIdOrderByCreatedAtDesc(adminId);
    }

    public Page<Notification> getForAdminPaged(Long adminId, Pageable pageable) {
        return notificationRepository.findByAdminIdOrderByCreatedAtDesc(adminId, pageable);
    }

    public long countUnread(Long adminId) {
        return notificationRepository.countByAdminIdAndReadFalse(adminId);
    }

    @Transactional
    public void markRead(Long notificationId) {
        notificationRepository.findById(notificationId).ifPresent(n -> {
            n.setRead(true);
            notificationRepository.save(n);
        });
    }

    @Transactional
    public void markAllRead(Long adminId) {
        notificationRepository.markAllReadForAdmin(adminId);
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public NotificationService(final NotificationRepository notificationRepository) {
        this.notificationRepository = notificationRepository;
    }
}
