// Generated by delombok at Sat Sep 26 12:28:47 IST 2026
package com.campus.complaint.controller;

import com.campus.complaint.dto.request.CreateAdminRequest;
import com.campus.complaint.dto.response.ApiResponse;
import com.campus.complaint.entity.Admin;
import com.campus.complaint.entity.Department;
import com.campus.complaint.service.AdminService;
import jakarta.validation.Valid;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.*;
import java.util.List;

@RestController
@RequestMapping("/api/admin-mgmt")
@PreAuthorize("hasRole(\'SUPER_ADMIN\')")
public class AdminManagementController {
    private final AdminService adminService;

    @GetMapping
    public ResponseEntity<ApiResponse<List<Admin>>> getAll() {
        return ResponseEntity.ok(ApiResponse.success(adminService.getAllAdmins()));
    }

    @GetMapping("/{id}")
    public ResponseEntity<ApiResponse<Admin>> getById(@PathVariable Long id) {
        return ResponseEntity.ok(ApiResponse.success(adminService.getById(id)));
    }

    @PostMapping
    public ResponseEntity<ApiResponse<Admin>> create(@Valid @RequestBody CreateAdminRequest req, @AuthenticationPrincipal Admin actor) {
        Admin admin = adminService.createAdmin(req, actor);
        return ResponseEntity.status(HttpStatus.CREATED).body(ApiResponse.success("Admin created", admin));
    }

    @PutMapping("/{id}/toggle-active")
    public ResponseEntity<ApiResponse<Admin>> toggleActive(@PathVariable Long id, @AuthenticationPrincipal Admin actor) {
        return ResponseEntity.ok(ApiResponse.success(adminService.toggleActive(id, actor)));
    }

    @DeleteMapping("/{id}")
    public ResponseEntity<ApiResponse<Void>> delete(@PathVariable Long id, @AuthenticationPrincipal Admin actor) {
        adminService.deleteAdmin(id, actor);
        return ResponseEntity.ok(ApiResponse.success("Admin deleted", null));
    }

    @GetMapping("/departments")
    public ResponseEntity<ApiResponse<List<Department>>> getDepartments() {
        return ResponseEntity.ok(ApiResponse.success(adminService.getAllDepartments()));
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public AdminManagementController(final AdminService adminService) {
        this.adminService = adminService;
    }
}
