// Generated by delombok at Sat Sep 26 12:28:47 IST 2026
package com.campus.complaint.controller;

import com.campus.complaint.dto.response.ApiResponse;
import com.campus.complaint.entity.AuditLog;
import com.campus.complaint.service.AuditLogService;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/audit-logs")
@PreAuthorize("hasRole(\'SUPER_ADMIN\')")
public class AuditLogController {
    private final AuditLogService auditLogService;

    @GetMapping
    public ResponseEntity<ApiResponse<Page<AuditLog>>> getAll(@RequestParam(defaultValue = "0") int page, @RequestParam(defaultValue = "50") int size) {
        Page<AuditLog> logs = auditLogService.getAll(PageRequest.of(page, size));
        return ResponseEntity.ok(ApiResponse.success(logs));
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public AuditLogController(final AuditLogService auditLogService) {
        this.auditLogService = auditLogService;
    }
}
