// Generated by delombok at Sat Sep 26 12:28:47 IST 2026
package com.campus.complaint.controller;

import com.campus.complaint.dto.request.*;
import com.campus.complaint.dto.response.ApiResponse;
import com.campus.complaint.dto.response.ComplaintResponse;
import com.campus.complaint.dto.response.DashboardResponse;
import com.campus.complaint.entity.Admin;
import com.campus.complaint.entity.Comment;
import com.campus.complaint.entity.Complaint;
import com.campus.complaint.entity.Escalation;
import com.campus.complaint.service.ComplaintService;
import jakarta.validation.Valid;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.*;
import java.util.List;
import java.util.Map;

@RestController
@RequestMapping("/api/complaints")
public class ComplaintController {
    private final ComplaintService complaintService;

    @GetMapping
    public ResponseEntity<ApiResponse<Page<ComplaintResponse>>> getAll(@RequestParam(required = false) String status, @RequestParam(required = false) String category, @RequestParam(required = false) String priority, @RequestParam(required = false) Long departmentId, @RequestParam(required = false) String search, @RequestParam(defaultValue = "0") int page, @RequestParam(defaultValue = "20") int size, @AuthenticationPrincipal Admin actor) {
        Pageable pageable = PageRequest.of(page, size);
        Page<ComplaintResponse> result = complaintService.getAllComplaints(status, category, priority, departmentId, search, actor, pageable);
        return ResponseEntity.ok(ApiResponse.success(result));
    }

    @GetMapping("/{complaintId}")
    public ResponseEntity<ApiResponse<ComplaintResponse>> getById(@PathVariable String complaintId) {
        return ResponseEntity.ok(ApiResponse.success(complaintService.getById(complaintId)));
    }

    @PostMapping
    public ResponseEntity<ApiResponse<ComplaintResponse>> create(@Valid @RequestBody CreateComplaintRequest req, @AuthenticationPrincipal Admin actor) {
        ComplaintResponse response = complaintService.createComplaint(req, actor);
        return ResponseEntity.status(HttpStatus.CREATED).body(ApiResponse.success("Complaint created", response));
    }

    @PutMapping("/{complaintId}/assign")
    @PreAuthorize("hasAnyRole(\'SUPER_ADMIN\', \'DEPARTMENT_ADMIN\')")
    public ResponseEntity<ApiResponse<ComplaintResponse>> assign(@PathVariable String complaintId, @Valid @RequestBody AssignComplaintRequest req, @AuthenticationPrincipal Admin actor) {
        return ResponseEntity.ok(ApiResponse.success("Assigned successfully", complaintService.assignHandler(complaintId, req, actor)));
    }

    @PutMapping("/{complaintId}/status")
    public ResponseEntity<ApiResponse<ComplaintResponse>> updateStatus(@PathVariable String complaintId, @Valid @RequestBody UpdateStatusRequest req, @AuthenticationPrincipal Admin actor) {
        return ResponseEntity.ok(ApiResponse.success("Status updated", complaintService.updateStatus(complaintId, req, actor)));
    }

    @PutMapping("/{complaintId}/priority")
    @PreAuthorize("hasAnyRole(\'SUPER_ADMIN\', \'DEPARTMENT_ADMIN\')")
    public ResponseEntity<ApiResponse<ComplaintResponse>> updatePriority(@PathVariable String complaintId, @RequestBody Map<String, String> body, @AuthenticationPrincipal Admin actor) {
        Complaint.Priority priority = Complaint.Priority.valueOf(body.get("priority"));
        return ResponseEntity.ok(ApiResponse.success("Priority updated", complaintService.updatePriority(complaintId, priority, actor)));
    }

    @PostMapping("/{complaintId}/comments")
    public ResponseEntity<ApiResponse<Comment>> addComment(@PathVariable String complaintId, @Valid @RequestBody AddCommentRequest req, @AuthenticationPrincipal Admin actor) {
        Comment comment = complaintService.addComment(complaintId, req, actor);
        return ResponseEntity.status(HttpStatus.CREATED).body(ApiResponse.success("Comment added", comment));
    }

    @GetMapping("/{complaintId}/comments")
    public ResponseEntity<ApiResponse<List<Comment>>> getComments(@PathVariable String complaintId) {
        return ResponseEntity.ok(ApiResponse.success(complaintService.getComments(complaintId)));
    }

    @PostMapping("/{complaintId}/escalate")
    @PreAuthorize("hasAnyRole(\'SUPER_ADMIN\', \'DEPARTMENT_ADMIN\')")
    public ResponseEntity<ApiResponse<ComplaintResponse>> escalate(@PathVariable String complaintId, @Valid @RequestBody EscalateRequest req, @AuthenticationPrincipal Admin actor) {
        return ResponseEntity.ok(ApiResponse.success("Escalated", complaintService.escalate(complaintId, req, actor)));
    }

    @GetMapping("/{complaintId}/escalations")
    public ResponseEntity<ApiResponse<List<Escalation>>> getEscalations(@PathVariable String complaintId) {
        return ResponseEntity.ok(ApiResponse.success(complaintService.getEscalations(complaintId)));
    }

    @PostMapping("/{complaintId}/resolve")
    public ResponseEntity<ApiResponse<ComplaintResponse>> resolve(@PathVariable String complaintId, @RequestBody(required = false) Map<String, String> body, @AuthenticationPrincipal Admin actor) {
        String note = body != null ? body.getOrDefault("note", "") : "";
        return ResponseEntity.ok(ApiResponse.success("Resolved", complaintService.resolve(complaintId, note, actor)));
    }

    @PostMapping("/{complaintId}/close")
    @PreAuthorize("hasAnyRole(\'SUPER_ADMIN\', \'DEPARTMENT_ADMIN\')")
    public ResponseEntity<ApiResponse<ComplaintResponse>> close(@PathVariable String complaintId, @AuthenticationPrincipal Admin actor) {
        return ResponseEntity.ok(ApiResponse.success("Closed", complaintService.close(complaintId, actor)));
    }

    @GetMapping("/students")
    public ResponseEntity<ApiResponse<?>> getStudents() {
        return ResponseEntity.ok(ApiResponse.success(complaintService.getAllStudents()));
    }

    @GetMapping("/handlers")
    public ResponseEntity<ApiResponse<?>> getHandlers() {
        return ResponseEntity.ok(ApiResponse.success(complaintService.getHandlers()));
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ComplaintController(final ComplaintService complaintService) {
        this.complaintService = complaintService;
    }
}
