// Generated by delombok at Sat Sep 26 12:28:47 IST 2026
package com.campus.complaint.controller;

import com.campus.complaint.dto.response.ApiResponse;
import com.campus.complaint.dto.response.DashboardResponse;
import com.campus.complaint.entity.Admin;
import com.campus.complaint.service.ComplaintService;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.*;
import java.util.Map;

@RestController
@RequestMapping("/api")
public class DashboardController {
    private final ComplaintService complaintService;

    @GetMapping("/dashboard")
    public ResponseEntity<ApiResponse<DashboardResponse>> getDashboard(@AuthenticationPrincipal Admin actor) {
        return ResponseEntity.ok(ApiResponse.success(complaintService.getDashboard(actor)));
    }

    @GetMapping("/reports")
    public ResponseEntity<ApiResponse<Map<String, Object>>> getReports() {
        return ResponseEntity.ok(ApiResponse.success(complaintService.getReports()));
    }

    @GetMapping("/health")
    public ResponseEntity<String> health() {
        return ResponseEntity.ok("Campus Complaint Portal - Running");
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public DashboardController(final ComplaintService complaintService) {
        this.complaintService = complaintService;
    }
}
