// Generated by delombok at Sat Sep 26 12:28:47 IST 2026
package com.campus.complaint.controller;

import com.campus.complaint.dto.response.ApiResponse;
import com.campus.complaint.entity.Admin;
import com.campus.complaint.entity.Notification;
import com.campus.complaint.service.NotificationService;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.*;
import java.util.Map;

@RestController
@RequestMapping("/api/notifications")
public class NotificationController {
    private final NotificationService notificationService;

    @GetMapping
    public ResponseEntity<ApiResponse<Page<Notification>>> getNotifications(@RequestParam(defaultValue = "0") int page, @RequestParam(defaultValue = "20") int size, @AuthenticationPrincipal Admin actor) {
        Page<Notification> notifications = notificationService.getForAdminPaged(actor.getId(), PageRequest.of(page, size));
        return ResponseEntity.ok(ApiResponse.success(notifications));
    }

    @GetMapping("/unread-count")
    public ResponseEntity<ApiResponse<Map<String, Long>>> getUnreadCount(@AuthenticationPrincipal Admin actor) {
        long count = notificationService.countUnread(actor.getId());
        return ResponseEntity.ok(ApiResponse.success(Map.of("count", count)));
    }

    @PutMapping("/{id}/read")
    public ResponseEntity<ApiResponse<Void>> markRead(@PathVariable Long id, @AuthenticationPrincipal Admin actor) {
        notificationService.markRead(id);
        return ResponseEntity.ok(ApiResponse.success("Marked as read", null));
    }

    @PutMapping("/mark-all-read")
    public ResponseEntity<ApiResponse<Void>> markAllRead(@AuthenticationPrincipal Admin actor) {
        notificationService.markAllRead(actor.getId());
        return ResponseEntity.ok(ApiResponse.success("All marked as read", null));
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public NotificationController(final NotificationService notificationService) {
        this.notificationService = notificationService;
    }
}
