// Generated by delombok at Sat Sep 26 12:28:47 IST 2026
package com.campus.complaint.config;

import com.campus.complaint.entity.*;
import com.campus.complaint.repository.*;
import org.springframework.boot.CommandLineRunner;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;
import java.time.LocalDateTime;
import java.util.List;

@Component
public class DataSeeder implements CommandLineRunner {
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(DataSeeder.class);
    private final AdminRepository adminRepository;
    private final StudentRepository studentRepository;
    private final DepartmentRepository departmentRepository;
    private final ComplaintRepository complaintRepository;
    private final EscalationRepository escalationRepository;
    private final PasswordEncoder passwordEncoder;

    @Override
    @Transactional
    public void run(String... args) {
        if (departmentRepository.count() == 0) {
            seedDepartments();
        }
        if (adminRepository.count() == 0) {
            seedAdmins();
        }
        if (studentRepository.count() == 0) {
            seedStudents();
        }
        if (complaintRepository.count() == 0) {
            log.info("Seeding complaints...");
            seedComplaints();
            log.info("Complaints seeded successfully!");
        }
    }

    private void seedDepartments() {
        List<Department> depts = List.of(dept("Information Technology", "IT", "IT department handling all technical issues"), dept("Hostel Administration", "HOSTEL", "Hostel and accommodation management"), dept("Transport Department", "TRANSPORT", "Campus transport and vehicle management"), dept("Facilities Management", "FACILITIES", "Infrastructure and maintenance"), dept("Academic Affairs", "ACADEMIC", "Academic issues and curriculum matters"), dept("Safety & Security", "SAFETY", "Campus safety and security concerns"), dept("General Administration", "GENERAL", "General administrative complaints"));
        departmentRepository.saveAll(depts);
        log.info("Departments seeded: {}", depts.size());
    }

    private Department dept(String name, String code, String desc) {
        Department d = new Department();
        d.setName(name);
        d.setCode(code);
        d.setDescription(desc);
        return d;
    }

    private void seedAdmins() {
        Department itDept = departmentRepository.findByCode("IT").orElseThrow();
        Department hostelDept = departmentRepository.findByCode("HOSTEL").orElseThrow();
        Department facilitiesDept = departmentRepository.findByCode("FACILITIES").orElseThrow();
        Department academicDept = departmentRepository.findByCode("ACADEMIC").orElseThrow();
        String pass = passwordEncoder.encode("Admin@123");
        String handlerPass = passwordEncoder.encode("Handler@123");
        // Super Admin
        adminRepository.save(admin("superadmin", "superadmin@campus.edu", pass, "Dr. Rajesh Kumar", Admin.Role.SUPER_ADMIN, null));
        // Department Admins
        adminRepository.save(admin("itadmin", "itadmin@campus.edu", pass, "Ms. Priya Sharma", Admin.Role.DEPARTMENT_ADMIN, itDept));
        adminRepository.save(admin("hosteladmin", "hosteladmin@campus.edu", pass, "Mr. Suresh Patel", Admin.Role.DEPARTMENT_ADMIN, hostelDept));
        // Complaint Handlers
        adminRepository.save(admin("handler1", "handler1@campus.edu", handlerPass, "Mr. Arjun Singh", Admin.Role.COMPLAINT_HANDLER, itDept));
        adminRepository.save(admin("handler2", "handler2@campus.edu", handlerPass, "Ms. Kavya Reddy", Admin.Role.COMPLAINT_HANDLER, hostelDept));
        adminRepository.save(admin("handler3", "handler3@campus.edu", handlerPass, "Mr. Vikram Nair", Admin.Role.COMPLAINT_HANDLER, facilitiesDept));
        adminRepository.save(admin("handler4", "handler4@campus.edu", handlerPass, "Ms. Ananya Iyer", Admin.Role.COMPLAINT_HANDLER, academicDept));
        log.info("Admins seeded: 7");
    }

    private Admin admin(String username, String email, String password, String fullName, Admin.Role role, Department dept) {
        Admin a = new Admin();
        a.setUsername(username);
        a.setEmail(email);
        a.setPassword(password);
        a.setFullName(fullName);
        a.setRole(role);
        a.setDepartment(dept);
        return a;
    }

    private void seedStudents() {
        List<Student> students = List.of(student("STU001", "Aarav Mehta", "aarav.mehta@student.campus.edu", "9876543210", "Computer Science", 2), student("STU002", "Diya Patel", "diya.patel@student.campus.edu", "9876543211", "Electrical Engineering", 3), student("STU003", "Rohan Gupta", "rohan.gupta@student.campus.edu", "9876543212", "Mechanical Engineering", 1), student("STU004", "Sneha Sharma", "sneha.sharma@student.campus.edu", "9876543213", "Civil Engineering", 4), student("STU005", "Karan Verma", "karan.verma@student.campus.edu", "9876543214", "Computer Science", 2), student("STU006", "Priya Nair", "priya.nair@student.campus.edu", "9876543215", "Electronics", 3), student("STU007", "Arjun Kumar", "arjun.kumar@student.campus.edu", "9876543216", "Mathematics", 1), student("STU008", "Ananya Singh", "ananya.singh@student.campus.edu", "9876543217", "Physics", 2), student("STU009", "Vijay Reddy", "vijay.reddy@student.campus.edu", "9876543218", "Chemistry", 4), student("STU010", "Meera Joshi", "meera.joshi@student.campus.edu", "9876543219", "Computer Science", 3), student("STU011", "Ravi Shankar", "ravi.shankar@student.campus.edu", "9876543220", "Electrical Engineering", 2), student("STU012", "Pooja Mishra", "pooja.mishra@student.campus.edu", "9876543221", "Mechanical Engineering", 1), student("STU013", "Aditya Rao", "aditya.rao@student.campus.edu", "9876543222", "Computer Science", 4), student("STU014", "Lakshmi Prasad", "lakshmi.prasad@student.campus.edu", "9876543223", "Civil Engineering", 2), student("STU015", "Dev Kapoor", "dev.kapoor@student.campus.edu", "9876543224", "Electronics", 3));
        studentRepository.saveAll(students);
        log.info("Students seeded: {}", students.size());
    }

    private Student student(String id, String name, String email, String phone, String dept, int year) {
        Student s = new Student();
        s.setStudentId(id);
        s.setFullName(name);
        s.setEmail(email);
        s.setPassword(passwordEncoder.encode("Student@123"));
        s.setPhone(phone);
        s.setDepartment(dept);
        s.setYearOfStudy(year);
        return s;
    }

    private Department getOrCreateDept(String name, String code, String desc) {
        return departmentRepository.findByCode(code)
                .orElseGet(() -> departmentRepository.save(dept(name, code, desc)));
    }

    private Admin getOrCreateAdmin(String username, String email, String password, String fullName, Admin.Role role, Department dept) {
        return adminRepository.findByUsername(username)
                .orElseGet(() -> adminRepository.save(admin(username, email, password, fullName, role, dept)));
    }

    private Student getStudent(List<Student> students, int index) {
        if (students.isEmpty()) {
            Student s = student("STU001", "Aarav Mehta", "aarav.mehta@student.campus.edu", "9876543210", "Computer Science", 2);
            return studentRepository.save(s);
        }
        return students.get(index % students.size());
    }

    private void seedComplaints() {
        Department itDept = getOrCreateDept("Information Technology", "IT", "IT department handling all technical issues");
        Department hostelDept = getOrCreateDept("Hostel Administration", "HOSTEL", "Hostel and accommodation management");
        Department facilitiesDept = getOrCreateDept("Facilities Management", "FACILITIES", "Infrastructure and maintenance");
        Department academicDept = getOrCreateDept("Academic Affairs", "ACADEMIC", "Academic issues and curriculum matters");
        Department generalDept = getOrCreateDept("General Administration", "GENERAL", "General administrative complaints");
        Department safetyDept = getOrCreateDept("Safety & Security", "SAFETY", "Campus safety and security concerns");

        String pass = passwordEncoder.encode("Admin@123");
        String handlerPass = passwordEncoder.encode("Handler@123");

        Admin superAdmin = getOrCreateAdmin("superadmin", "superadmin@campus.edu", pass, "Dr. Rajesh Kumar", Admin.Role.SUPER_ADMIN, null);
        Admin handler1 = getOrCreateAdmin("handler1", "handler1@campus.edu", handlerPass, "Mr. Arjun Singh", Admin.Role.COMPLAINT_HANDLER, itDept);
        Admin handler2 = getOrCreateAdmin("handler2", "handler2@campus.edu", handlerPass, "Ms. Kavya Reddy", Admin.Role.COMPLAINT_HANDLER, hostelDept);
        Admin handler3 = getOrCreateAdmin("handler3", "handler3@campus.edu", handlerPass, "Mr. Vikram Nair", Admin.Role.COMPLAINT_HANDLER, facilitiesDept);
        Admin handler4 = getOrCreateAdmin("handler4", "handler4@campus.edu", handlerPass, "Ms. Ananya Iyer", Admin.Role.COMPLAINT_HANDLER, academicDept);

        List<Student> students = studentRepository.findAll();
        if (students.isEmpty()) {
            seedStudents();
            students = studentRepository.findAll();
        }

        int counter = 1;
        // 1. NEW complaint
        Complaint c1 = complaint(counter++, getStudent(students, 0), "Campus WiFi not working in Block A", "WiFi in Block A has been down for 3 days. Students cannot access online resources.", Complaint.Category.IT, Complaint.Priority.HIGH, itDept, null, Complaint.Status.NEW);
        complaintRepository.save(c1);
        // 2. VALIDATING
        Complaint c2 = complaint(counter++, getStudent(students, 1), "Broken water pipe in Hostel Room 204", "There is a broken water pipe leaking water into room 204. Urgent repair needed.", Complaint.Category.HOSTEL, Complaint.Priority.CRITICAL, hostelDept, null, Complaint.Status.VALIDATING);
        complaintRepository.save(c2);
        // 3. ASSIGNED
        Complaint c3 = complaint(counter++, getStudent(students, 2), "Library AC not functioning", "The air conditioning in the main library has stopped working. Very uncomfortable for students.", Complaint.Category.INFRASTRUCTURE, Complaint.Priority.MEDIUM, facilitiesDept, handler3, Complaint.Status.ASSIGNED);
        complaintRepository.save(c3);
        // 4. IN_PROGRESS
        Complaint c4 = complaint(counter++, getStudent(students, 3), "Projector broken in Classroom 301", "The projector in Room 301 is broken. Cannot conduct proper lectures.", Complaint.Category.IT, Complaint.Priority.HIGH, itDept, handler1, Complaint.Status.IN_PROGRESS);
        complaintRepository.save(c4);
        // 5. RESOLVED
        Complaint c5 = complaint(counter++, getStudent(students, 4), "Bus route 5 not running on time", "Bus route 5 is consistently 30-45 minutes late causing students to miss morning classes.", Complaint.Category.TRANSPORT, Complaint.Priority.MEDIUM, null, null, Complaint.Status.RESOLVED);
        c5.setResolvedAt(LocalDateTime.now().minusDays(2));
        c5.setResolutionNote("Bus schedule has been adjusted. New timing: 7:30 AM.");
        complaintRepository.save(c5);
        // 6. CLOSED
        Complaint c6 = complaint(counter++, getStudent(students, 5), "Canteen food quality poor", "The food served in the main canteen is often stale and unhygienic.", Complaint.Category.CANTEEN, Complaint.Priority.LOW, generalDept, null, Complaint.Status.CLOSED);
        c6.setResolvedAt(LocalDateTime.now().minusDays(5));
        c6.setClosedAt(LocalDateTime.now().minusDays(3));
        c6.setResolutionNote("Canteen vendor has been warned and new hygiene standards implemented.");
        complaintRepository.save(c6);
        // 7. ESCALATED
        Complaint c7 = complaint(counter++, getStudent(students, 6), "Exam result not uploaded", "Results for the mid-semester examination have not been uploaded on the portal for 2 weeks.", Complaint.Category.ACADEMIC, Complaint.Priority.HIGH, academicDept, handler4, Complaint.Status.ESCALATED);
        complaintRepository.save(c7);
        // Create escalation for c7
        Escalation esc1 = new Escalation();
        esc1.setComplaint(c7);
        esc1.setEscalatedBy(superAdmin);
        esc1.setReason("No action taken in 2 weeks despite HIGH priority. Escalating to department head.");
        esc1.setPreviousAssignee(handler4);
        escalationRepository.save(esc1);
        // 8. OVERDUE critical complaint
        Complaint c8 = complaint(counter++, getStudent(students, 7), "Electrical hazard in Lab 5", "There is a live exposed wire in Lab 5. Immediate action required to prevent accidents.", Complaint.Category.SAFETY, Complaint.Priority.CRITICAL, safetyDept, handler3, Complaint.Status.IN_PROGRESS);
        c8.setDueDate(LocalDateTime.now().minusHours(8)); // Already overdue
        complaintRepository.save(c8);
        // 9. Another overdue
        Complaint c9 = complaint(counter++, getStudent(students, 8), "Hostel common room lights not working", "All lights in the hostel common room have been non-functional for 5 days.", Complaint.Category.HOSTEL, Complaint.Priority.MEDIUM, hostelDept, handler2, Complaint.Status.IN_PROGRESS);
        c9.setDueDate(LocalDateTime.now().minusDays(2)); // Overdue
        complaintRepository.save(c9);
        // 10. NEW - Approaching SLA
        Complaint c10 = complaint(counter++, getStudent(students, 9), "Printer not working in Computer Lab", "All 5 printers in Computer Lab 2 are non-functional. Students cannot print assignments.", Complaint.Category.IT, Complaint.Priority.HIGH, itDept, handler1, Complaint.Status.ASSIGNED);
        c10.setDueDate(LocalDateTime.now().plusHours(3)); // Approaching SLA
        complaintRepository.save(c10);
        // 11-15. Additional complaints
        Complaint c11 = complaint(counter++, getStudent(students, 10), "Scholarship portal login failing", "Cannot log into the scholarship portal to submit application before deadline.", Complaint.Category.IT, Complaint.Priority.CRITICAL, itDept, handler1, Complaint.Status.IN_PROGRESS);
        complaintRepository.save(c11);
        Complaint c12 = complaint(counter++, getStudent(students, 11), "Classroom 102 seating inadequate", "Classroom 102 has 60 students but only 45 seats. Some students must stand.", Complaint.Category.INFRASTRUCTURE, Complaint.Priority.HIGH, facilitiesDept, handler3, Complaint.Status.ASSIGNED);
        complaintRepository.save(c12);
        Complaint c13 = complaint(counter++, getStudent(students, 12), "Garbage not collected in Hostel Block C", "Garbage bins in Hostel Block C haven't been collected for 4 days.", Complaint.Category.MAINTENANCE, Complaint.Priority.MEDIUM, facilitiesDept, null, Complaint.Status.NEW);
        complaintRepository.save(c13);
        Complaint c14 = complaint(counter++, getStudent(students, 13), "Attendance marked incorrect", "My attendance for CS-301 on Sept 15 shows absent but I was present.", Complaint.Category.ACADEMIC, Complaint.Priority.MEDIUM, academicDept, handler4, Complaint.Status.IN_PROGRESS);
        complaintRepository.save(c14);
        Complaint c15 = complaint(counter++, getStudent(students, 14), "Gym equipment broken", "Multiple gym equipment items are broken and poses risk of injury.", Complaint.Category.INFRASTRUCTURE, Complaint.Priority.HIGH, facilitiesDept, handler3, Complaint.Status.STUDENT_VERIFICATION);
        c15.setResolvedAt(LocalDateTime.now().minusDays(1));
        c15.setResolutionNote("All broken equipment has been replaced and serviced.");
        complaintRepository.save(c15);
        // 16-20. More variety
        Complaint c16 = complaint(counter++, getStudent(students, 0), "Campus network blocked gaming sites", "The campus network is blocking educational gaming sites used for programming practice.", Complaint.Category.IT, Complaint.Priority.LOW, itDept, null, Complaint.Status.REJECTED);
        c16.setRejectionReason("Gaming sites are blocked as per campus IT policy. This is not a complaint matter.");
        complaintRepository.save(c16);
        Complaint c17 = complaint(counter++, getStudent(students, 1), "Hostel water supply cut at night", "Water supply in Hostel Block B is being cut at 11 PM. Students need water late at night too.", Complaint.Category.HOSTEL, Complaint.Priority.HIGH, hostelDept, handler2, Complaint.Status.RESOLVED);
        c17.setResolvedAt(LocalDateTime.now().minusDays(1));
        c17.setResolutionNote("Water supply has been extended to 24 hours per day.");
        complaintRepository.save(c17);
        Complaint c18 = complaint(counter++, getStudent(students, 2), "Canteen closed during exam hours", "Main canteen closes at 3 PM but exams often run until 5 PM. Students have no food.", Complaint.Category.CANTEEN, Complaint.Priority.MEDIUM, generalDept, null, Complaint.Status.VALIDATING);
        complaintRepository.save(c18);
        Complaint c19 = complaint(counter++, getStudent(students, 3), "Stray dogs on campus", "Multiple stray dogs on campus are aggressive and causing fear among students.", Complaint.Category.SAFETY, Complaint.Priority.HIGH, safetyDept, null, Complaint.Status.NEW);
        complaintRepository.save(c19);
        Complaint c20 = complaint(counter++, getStudent(students, 4), "Chemistry lab chemicals expired", "Several chemicals in Chem Lab 3 are past their expiry date. Safety concern.", Complaint.Category.SAFETY, Complaint.Priority.CRITICAL, safetyDept, handler3, Complaint.Status.IN_PROGRESS);
        complaintRepository.save(c20);
        log.info("Complaints seeded: 20");
    }

    private Complaint complaint(int num, Student student, String title, String desc, Complaint.Category category, Complaint.Priority priority, Department dept, Admin handler, Complaint.Status status) {
        Complaint c = new Complaint();
        c.setComplaintId(String.format("CMP-%04d", num));
        c.setStudent(student);
        c.setTitle(title);
        c.setDescription(desc);
        c.setCategory(category);
        c.setPriority(priority);
        c.setDepartment(dept);
        c.setAssignedHandler(handler);
        c.setStatus(status);
        c.setDueDate(LocalDateTime.now().plusHours(priority.getSlaHours()));
        return c;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public DataSeeder(final AdminRepository adminRepository, final StudentRepository studentRepository, final DepartmentRepository departmentRepository, final ComplaintRepository complaintRepository, final EscalationRepository escalationRepository, final PasswordEncoder passwordEncoder) {
        this.adminRepository = adminRepository;
        this.studentRepository = studentRepository;
        this.departmentRepository = departmentRepository;
        this.complaintRepository = complaintRepository;
        this.escalationRepository = escalationRepository;
        this.passwordEncoder = passwordEncoder;
    }
}
