// Generated by delombok at Sat Sep 26 12:28:47 IST 2026
package com.campus.complaint.entity;

import jakarta.persistence.*;
import org.hibernate.annotations.CreationTimestamp;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.time.LocalDateTime;

@Entity
@Table(name = "audit_logs")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class AuditLog {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "admin_id")
    @JsonIgnoreProperties({"password", "hibernateLazyInitializer", "handler"})
    private Admin admin;
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "complaint_id")
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
    private Complaint complaint;
    @Column(nullable = false, length = 100)
    private String action;
    @Column(name = "entity_type", length = 50)
    private String entityType;
    @Column(name = "old_value", columnDefinition = "TEXT")
    private String oldValue;
    @Column(name = "new_value", columnDefinition = "TEXT")
    private String newValue;
    @Column(columnDefinition = "TEXT")
    private String description;
    @Column(name = "ip_address", length = 50)
    private String ipAddress;
    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Admin getAdmin() {
        return this.admin;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Complaint getComplaint() {
        return this.complaint;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getAction() {
        return this.action;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getEntityType() {
        return this.entityType;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getOldValue() {
        return this.oldValue;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNewValue() {
        return this.newValue;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getIpAddress() {
        return this.ipAddress;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAdmin(final Admin admin) {
        this.admin = admin;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setComplaint(final Complaint complaint) {
        this.complaint = complaint;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAction(final String action) {
        this.action = action;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEntityType(final String entityType) {
        this.entityType = entityType;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setOldValue(final String oldValue) {
        this.oldValue = oldValue;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNewValue(final String newValue) {
        this.newValue = newValue;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDescription(final String description) {
        this.description = description;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setIpAddress(final String ipAddress) {
        this.ipAddress = ipAddress;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof AuditLog)) return false;
        final AuditLog other = (AuditLog) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$admin = this.getAdmin();
        final java.lang.Object other$admin = other.getAdmin();
        if (this$admin == null ? other$admin != null : !this$admin.equals(other$admin)) return false;
        final java.lang.Object this$complaint = this.getComplaint();
        final java.lang.Object other$complaint = other.getComplaint();
        if (this$complaint == null ? other$complaint != null : !this$complaint.equals(other$complaint)) return false;
        final java.lang.Object this$action = this.getAction();
        final java.lang.Object other$action = other.getAction();
        if (this$action == null ? other$action != null : !this$action.equals(other$action)) return false;
        final java.lang.Object this$entityType = this.getEntityType();
        final java.lang.Object other$entityType = other.getEntityType();
        if (this$entityType == null ? other$entityType != null : !this$entityType.equals(other$entityType)) return false;
        final java.lang.Object this$oldValue = this.getOldValue();
        final java.lang.Object other$oldValue = other.getOldValue();
        if (this$oldValue == null ? other$oldValue != null : !this$oldValue.equals(other$oldValue)) return false;
        final java.lang.Object this$newValue = this.getNewValue();
        final java.lang.Object other$newValue = other.getNewValue();
        if (this$newValue == null ? other$newValue != null : !this$newValue.equals(other$newValue)) return false;
        final java.lang.Object this$description = this.getDescription();
        final java.lang.Object other$description = other.getDescription();
        if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
        final java.lang.Object this$ipAddress = this.getIpAddress();
        final java.lang.Object other$ipAddress = other.getIpAddress();
        if (this$ipAddress == null ? other$ipAddress != null : !this$ipAddress.equals(other$ipAddress)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof AuditLog;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $admin = this.getAdmin();
        result = result * PRIME + ($admin == null ? 43 : $admin.hashCode());
        final java.lang.Object $complaint = this.getComplaint();
        result = result * PRIME + ($complaint == null ? 43 : $complaint.hashCode());
        final java.lang.Object $action = this.getAction();
        result = result * PRIME + ($action == null ? 43 : $action.hashCode());
        final java.lang.Object $entityType = this.getEntityType();
        result = result * PRIME + ($entityType == null ? 43 : $entityType.hashCode());
        final java.lang.Object $oldValue = this.getOldValue();
        result = result * PRIME + ($oldValue == null ? 43 : $oldValue.hashCode());
        final java.lang.Object $newValue = this.getNewValue();
        result = result * PRIME + ($newValue == null ? 43 : $newValue.hashCode());
        final java.lang.Object $description = this.getDescription();
        result = result * PRIME + ($description == null ? 43 : $description.hashCode());
        final java.lang.Object $ipAddress = this.getIpAddress();
        result = result * PRIME + ($ipAddress == null ? 43 : $ipAddress.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "AuditLog(id=" + this.getId() + ", admin=" + this.getAdmin() + ", complaint=" + this.getComplaint() + ", action=" + this.getAction() + ", entityType=" + this.getEntityType() + ", oldValue=" + this.getOldValue() + ", newValue=" + this.getNewValue() + ", description=" + this.getDescription() + ", ipAddress=" + this.getIpAddress() + ", createdAt=" + this.getCreatedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public AuditLog() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public AuditLog(final Long id, final Admin admin, final Complaint complaint, final String action, final String entityType, final String oldValue, final String newValue, final String description, final String ipAddress, final LocalDateTime createdAt) {
        this.id = id;
        this.admin = admin;
        this.complaint = complaint;
        this.action = action;
        this.entityType = entityType;
        this.oldValue = oldValue;
        this.newValue = newValue;
        this.description = description;
        this.ipAddress = ipAddress;
        this.createdAt = createdAt;
    }
}
