// Generated by delombok at Sat Sep 26 12:28:47 IST 2026
package com.campus.complaint.entity;

import jakarta.persistence.*;
import org.hibernate.annotations.CreationTimestamp;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.time.LocalDateTime;

@Entity
@Table(name = "comments")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Comment {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "complaint_id", nullable = false)
    private Complaint complaint;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "admin_id")
    private Admin admin;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "student_id")
    private Student student;
    @Column(name = "author_name", length = 100)
    private String authorName;
    @Column(name = "author_role", length = 50)
    private String authorRole;
    @Column(nullable = false, columnDefinition = "TEXT")
    private String content;
    @Column(name = "is_internal")
    private boolean internal = false;
    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Complaint getComplaint() {
        return this.complaint;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Admin getAdmin() {
        return this.admin;
    }

    public Student getStudent() {
        return this.student;
    }

    public void setStudent(Student student) {
        this.student = student;
    }

    public String getAuthorName() {
        return this.authorName;
    }

    public void setAuthorName(String authorName) {
        this.authorName = authorName;
    }

    public String getAuthorRole() {
        return this.authorRole;
    }

    public void setAuthorRole(String authorRole) {
        this.authorRole = authorRole;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getContent() {
        return this.content;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean isInternal() {
        return this.internal;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setComplaint(final Complaint complaint) {
        this.complaint = complaint;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAdmin(final Admin admin) {
        this.admin = admin;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setContent(final String content) {
        this.content = content;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setInternal(final boolean internal) {
        this.internal = internal;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Comment)) return false;
        final Comment other = (Comment) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.isInternal() != other.isInternal()) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$complaint = this.getComplaint();
        final java.lang.Object other$complaint = other.getComplaint();
        if (this$complaint == null ? other$complaint != null : !this$complaint.equals(other$complaint)) return false;
        final java.lang.Object this$admin = this.getAdmin();
        final java.lang.Object other$admin = other.getAdmin();
        if (this$admin == null ? other$admin != null : !this$admin.equals(other$admin)) return false;
        final java.lang.Object this$content = this.getContent();
        final java.lang.Object other$content = other.getContent();
        if (this$content == null ? other$content != null : !this$content.equals(other$content)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Comment;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + (this.isInternal() ? 79 : 97);
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $complaint = this.getComplaint();
        result = result * PRIME + ($complaint == null ? 43 : $complaint.hashCode());
        final java.lang.Object $admin = this.getAdmin();
        result = result * PRIME + ($admin == null ? 43 : $admin.hashCode());
        final java.lang.Object $content = this.getContent();
        result = result * PRIME + ($content == null ? 43 : $content.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "Comment(id=" + this.getId() + ", complaint=" + this.getComplaint() + ", admin=" + this.getAdmin() + ", content=" + this.getContent() + ", internal=" + this.isInternal() + ", createdAt=" + this.getCreatedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Comment() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Comment(final Long id, final Complaint complaint, final Admin admin, final String content, final boolean internal, final LocalDateTime createdAt) {
        this.id = id;
        this.complaint = complaint;
        this.admin = admin;
        this.content = content;
        this.internal = internal;
        this.createdAt = createdAt;
    }
}
