// Generated by delombok at Sat Sep 26 12:28:47 IST 2026
package com.campus.complaint.entity;

import jakarta.persistence.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.time.LocalDateTime;

@Entity
@Table(name = "complaints")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Complaint {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(name = "complaint_id", nullable = false, unique = true, length = 20)
    private String complaintId;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "student_id", nullable = false)
    private Student student;
    @Column(nullable = false, length = 255)
    private String title;
    @Column(nullable = false, columnDefinition = "TEXT")
    private String description;
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Category category;
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Priority priority;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "department_id")
    private Department department;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "assigned_handler_id")
    private Admin assignedHandler;
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Status status = Status.NEW;
    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;
    @UpdateTimestamp
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;
    @Column(name = "due_date")
    private LocalDateTime dueDate;
    @Column(name = "resolved_at")
    private LocalDateTime resolvedAt;
    @Column(name = "closed_at")
    private LocalDateTime closedAt;
    @Column(name = "rejection_reason", columnDefinition = "TEXT")
    private String rejectionReason;
    @Column(name = "resolution_note", columnDefinition = "TEXT")
    private String resolutionNote;


    public enum Category {
        ACADEMIC, INFRASTRUCTURE, HOSTEL, TRANSPORT, CANTEEN, IT, MAINTENANCE, SAFETY, FACILITY, OTHER;

        @com.fasterxml.jackson.annotation.JsonCreator
        public static Category fromString(String value) {
            if (value == null || value.isBlank()) return OTHER;
            String clean = value.trim().toUpperCase();
            if ("FACILITIES".equals(clean) || "FACILITY".equals(clean)) return INFRASTRUCTURE;
            for (Category c : Category.values()) {
                if (c.name().equalsIgnoreCase(clean)) return c;
            }
            return OTHER;
        }
    }


    public enum Priority {
        LOW, MEDIUM, HIGH, CRITICAL;

        @com.fasterxml.jackson.annotation.JsonCreator
        public static Priority fromString(String value) {
            if (value == null || value.isBlank()) return MEDIUM;
            String clean = value.trim().toUpperCase();
            for (Priority p : Priority.values()) {
                if (p.name().equalsIgnoreCase(clean)) return p;
            }
            return MEDIUM;
        }

        public long getSlaHours() {
            return switch (this) {
                case LOW -> 168;
                // 7 days
                case MEDIUM -> 72;
                // 3 days
                case HIGH -> 24;
                // 24 hours
                case CRITICAL -> 4;
                // 4 hours
            };
        }
    }


    public enum Status {
        NEW, VALIDATING, ASSIGNED, IN_PROGRESS, RESOLVED, STUDENT_VERIFICATION, CLOSED, REJECTED, ESCALATED, REOPENED;

        public boolean canTransitionTo(Status next) {
            return switch (this) {
                case NEW -> next == VALIDATING || next == REJECTED;
                case VALIDATING -> next == ASSIGNED || next == REJECTED;
                case ASSIGNED -> next == IN_PROGRESS || next == ESCALATED;
                case IN_PROGRESS -> next == RESOLVED || next == ESCALATED;
                case RESOLVED -> next == STUDENT_VERIFICATION || next == IN_PROGRESS;
                case STUDENT_VERIFICATION -> next == CLOSED || next == REOPENED;
                case ESCALATED -> next == IN_PROGRESS || next == ASSIGNED;
                case REOPENED -> next == IN_PROGRESS;
                case CLOSED -> false;
                case REJECTED -> false;
            };
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getComplaintId() {
        return this.complaintId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Student getStudent() {
        return this.student;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTitle() {
        return this.title;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Category getCategory() {
        return this.category;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Priority getPriority() {
        return this.priority;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Department getDepartment() {
        return this.department;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Admin getAssignedHandler() {
        return this.assignedHandler;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Status getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getDueDate() {
        return this.dueDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getResolvedAt() {
        return this.resolvedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getClosedAt() {
        return this.closedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getRejectionReason() {
        return this.rejectionReason;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getResolutionNote() {
        return this.resolutionNote;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setComplaintId(final String complaintId) {
        this.complaintId = complaintId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStudent(final Student student) {
        this.student = student;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTitle(final String title) {
        this.title = title;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDescription(final String description) {
        this.description = description;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCategory(final Category category) {
        this.category = category;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPriority(final Priority priority) {
        this.priority = priority;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDepartment(final Department department) {
        this.department = department;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAssignedHandler(final Admin assignedHandler) {
        this.assignedHandler = assignedHandler;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatus(final Status status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUpdatedAt(final LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDueDate(final LocalDateTime dueDate) {
        this.dueDate = dueDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setResolvedAt(final LocalDateTime resolvedAt) {
        this.resolvedAt = resolvedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setClosedAt(final LocalDateTime closedAt) {
        this.closedAt = closedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setRejectionReason(final String rejectionReason) {
        this.rejectionReason = rejectionReason;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setResolutionNote(final String resolutionNote) {
        this.resolutionNote = resolutionNote;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Complaint)) return false;
        final Complaint other = (Complaint) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$complaintId = this.getComplaintId();
        final java.lang.Object other$complaintId = other.getComplaintId();
        if (this$complaintId == null ? other$complaintId != null : !this$complaintId.equals(other$complaintId)) return false;
        final java.lang.Object this$student = this.getStudent();
        final java.lang.Object other$student = other.getStudent();
        if (this$student == null ? other$student != null : !this$student.equals(other$student)) return false;
        final java.lang.Object this$title = this.getTitle();
        final java.lang.Object other$title = other.getTitle();
        if (this$title == null ? other$title != null : !this$title.equals(other$title)) return false;
        final java.lang.Object this$description = this.getDescription();
        final java.lang.Object other$description = other.getDescription();
        if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
        final java.lang.Object this$category = this.getCategory();
        final java.lang.Object other$category = other.getCategory();
        if (this$category == null ? other$category != null : !this$category.equals(other$category)) return false;
        final java.lang.Object this$priority = this.getPriority();
        final java.lang.Object other$priority = other.getPriority();
        if (this$priority == null ? other$priority != null : !this$priority.equals(other$priority)) return false;
        final java.lang.Object this$department = this.getDepartment();
        final java.lang.Object other$department = other.getDepartment();
        if (this$department == null ? other$department != null : !this$department.equals(other$department)) return false;
        final java.lang.Object this$assignedHandler = this.getAssignedHandler();
        final java.lang.Object other$assignedHandler = other.getAssignedHandler();
        if (this$assignedHandler == null ? other$assignedHandler != null : !this$assignedHandler.equals(other$assignedHandler)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        final java.lang.Object this$updatedAt = this.getUpdatedAt();
        final java.lang.Object other$updatedAt = other.getUpdatedAt();
        if (this$updatedAt == null ? other$updatedAt != null : !this$updatedAt.equals(other$updatedAt)) return false;
        final java.lang.Object this$dueDate = this.getDueDate();
        final java.lang.Object other$dueDate = other.getDueDate();
        if (this$dueDate == null ? other$dueDate != null : !this$dueDate.equals(other$dueDate)) return false;
        final java.lang.Object this$resolvedAt = this.getResolvedAt();
        final java.lang.Object other$resolvedAt = other.getResolvedAt();
        if (this$resolvedAt == null ? other$resolvedAt != null : !this$resolvedAt.equals(other$resolvedAt)) return false;
        final java.lang.Object this$closedAt = this.getClosedAt();
        final java.lang.Object other$closedAt = other.getClosedAt();
        if (this$closedAt == null ? other$closedAt != null : !this$closedAt.equals(other$closedAt)) return false;
        final java.lang.Object this$rejectionReason = this.getRejectionReason();
        final java.lang.Object other$rejectionReason = other.getRejectionReason();
        if (this$rejectionReason == null ? other$rejectionReason != null : !this$rejectionReason.equals(other$rejectionReason)) return false;
        final java.lang.Object this$resolutionNote = this.getResolutionNote();
        final java.lang.Object other$resolutionNote = other.getResolutionNote();
        if (this$resolutionNote == null ? other$resolutionNote != null : !this$resolutionNote.equals(other$resolutionNote)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Complaint;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $complaintId = this.getComplaintId();
        result = result * PRIME + ($complaintId == null ? 43 : $complaintId.hashCode());
        final java.lang.Object $student = this.getStudent();
        result = result * PRIME + ($student == null ? 43 : $student.hashCode());
        final java.lang.Object $title = this.getTitle();
        result = result * PRIME + ($title == null ? 43 : $title.hashCode());
        final java.lang.Object $description = this.getDescription();
        result = result * PRIME + ($description == null ? 43 : $description.hashCode());
        final java.lang.Object $category = this.getCategory();
        result = result * PRIME + ($category == null ? 43 : $category.hashCode());
        final java.lang.Object $priority = this.getPriority();
        result = result * PRIME + ($priority == null ? 43 : $priority.hashCode());
        final java.lang.Object $department = this.getDepartment();
        result = result * PRIME + ($department == null ? 43 : $department.hashCode());
        final java.lang.Object $assignedHandler = this.getAssignedHandler();
        result = result * PRIME + ($assignedHandler == null ? 43 : $assignedHandler.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        final java.lang.Object $updatedAt = this.getUpdatedAt();
        result = result * PRIME + ($updatedAt == null ? 43 : $updatedAt.hashCode());
        final java.lang.Object $dueDate = this.getDueDate();
        result = result * PRIME + ($dueDate == null ? 43 : $dueDate.hashCode());
        final java.lang.Object $resolvedAt = this.getResolvedAt();
        result = result * PRIME + ($resolvedAt == null ? 43 : $resolvedAt.hashCode());
        final java.lang.Object $closedAt = this.getClosedAt();
        result = result * PRIME + ($closedAt == null ? 43 : $closedAt.hashCode());
        final java.lang.Object $rejectionReason = this.getRejectionReason();
        result = result * PRIME + ($rejectionReason == null ? 43 : $rejectionReason.hashCode());
        final java.lang.Object $resolutionNote = this.getResolutionNote();
        result = result * PRIME + ($resolutionNote == null ? 43 : $resolutionNote.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "Complaint(id=" + this.getId() + ", complaintId=" + this.getComplaintId() + ", student=" + this.getStudent() + ", title=" + this.getTitle() + ", description=" + this.getDescription() + ", category=" + this.getCategory() + ", priority=" + this.getPriority() + ", department=" + this.getDepartment() + ", assignedHandler=" + this.getAssignedHandler() + ", status=" + this.getStatus() + ", createdAt=" + this.getCreatedAt() + ", updatedAt=" + this.getUpdatedAt() + ", dueDate=" + this.getDueDate() + ", resolvedAt=" + this.getResolvedAt() + ", closedAt=" + this.getClosedAt() + ", rejectionReason=" + this.getRejectionReason() + ", resolutionNote=" + this.getResolutionNote() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Complaint() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Complaint(final Long id, final String complaintId, final Student student, final String title, final String description, final Category category, final Priority priority, final Department department, final Admin assignedHandler, final Status status, final LocalDateTime createdAt, final LocalDateTime updatedAt, final LocalDateTime dueDate, final LocalDateTime resolvedAt, final LocalDateTime closedAt, final String rejectionReason, final String resolutionNote) {
        this.id = id;
        this.complaintId = complaintId;
        this.student = student;
        this.title = title;
        this.description = description;
        this.category = category;
        this.priority = priority;
        this.department = department;
        this.assignedHandler = assignedHandler;
        this.status = status;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.dueDate = dueDate;
        this.resolvedAt = resolvedAt;
        this.closedAt = closedAt;
        this.rejectionReason = rejectionReason;
        this.resolutionNote = resolutionNote;
    }
}
