// Generated by delombok at Sat Sep 26 12:28:47 IST 2026
package com.campus.complaint.entity;

import jakarta.persistence.*;
import org.hibernate.annotations.CreationTimestamp;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.time.LocalDateTime;

@Entity
@Table(name = "escalations")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Escalation {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "complaint_id", nullable = false)
    private Complaint complaint;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "escalated_by_id", nullable = false)
    private Admin escalatedBy;
    @Column(nullable = false, columnDefinition = "TEXT")
    private String reason;
    @CreationTimestamp
    @Column(name = "escalated_at", updatable = false)
    private LocalDateTime escalatedAt;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "previous_assignee_id")
    private Admin previousAssignee;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "new_assignee_id")
    private Admin newAssignee;
    @Column(nullable = false)
    private boolean resolved = false;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Complaint getComplaint() {
        return this.complaint;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Admin getEscalatedBy() {
        return this.escalatedBy;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getReason() {
        return this.reason;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getEscalatedAt() {
        return this.escalatedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Admin getPreviousAssignee() {
        return this.previousAssignee;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Admin getNewAssignee() {
        return this.newAssignee;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean isResolved() {
        return this.resolved;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setComplaint(final Complaint complaint) {
        this.complaint = complaint;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEscalatedBy(final Admin escalatedBy) {
        this.escalatedBy = escalatedBy;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setReason(final String reason) {
        this.reason = reason;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEscalatedAt(final LocalDateTime escalatedAt) {
        this.escalatedAt = escalatedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPreviousAssignee(final Admin previousAssignee) {
        this.previousAssignee = previousAssignee;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNewAssignee(final Admin newAssignee) {
        this.newAssignee = newAssignee;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setResolved(final boolean resolved) {
        this.resolved = resolved;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Escalation)) return false;
        final Escalation other = (Escalation) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.isResolved() != other.isResolved()) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$complaint = this.getComplaint();
        final java.lang.Object other$complaint = other.getComplaint();
        if (this$complaint == null ? other$complaint != null : !this$complaint.equals(other$complaint)) return false;
        final java.lang.Object this$escalatedBy = this.getEscalatedBy();
        final java.lang.Object other$escalatedBy = other.getEscalatedBy();
        if (this$escalatedBy == null ? other$escalatedBy != null : !this$escalatedBy.equals(other$escalatedBy)) return false;
        final java.lang.Object this$reason = this.getReason();
        final java.lang.Object other$reason = other.getReason();
        if (this$reason == null ? other$reason != null : !this$reason.equals(other$reason)) return false;
        final java.lang.Object this$escalatedAt = this.getEscalatedAt();
        final java.lang.Object other$escalatedAt = other.getEscalatedAt();
        if (this$escalatedAt == null ? other$escalatedAt != null : !this$escalatedAt.equals(other$escalatedAt)) return false;
        final java.lang.Object this$previousAssignee = this.getPreviousAssignee();
        final java.lang.Object other$previousAssignee = other.getPreviousAssignee();
        if (this$previousAssignee == null ? other$previousAssignee != null : !this$previousAssignee.equals(other$previousAssignee)) return false;
        final java.lang.Object this$newAssignee = this.getNewAssignee();
        final java.lang.Object other$newAssignee = other.getNewAssignee();
        if (this$newAssignee == null ? other$newAssignee != null : !this$newAssignee.equals(other$newAssignee)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Escalation;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + (this.isResolved() ? 79 : 97);
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $complaint = this.getComplaint();
        result = result * PRIME + ($complaint == null ? 43 : $complaint.hashCode());
        final java.lang.Object $escalatedBy = this.getEscalatedBy();
        result = result * PRIME + ($escalatedBy == null ? 43 : $escalatedBy.hashCode());
        final java.lang.Object $reason = this.getReason();
        result = result * PRIME + ($reason == null ? 43 : $reason.hashCode());
        final java.lang.Object $escalatedAt = this.getEscalatedAt();
        result = result * PRIME + ($escalatedAt == null ? 43 : $escalatedAt.hashCode());
        final java.lang.Object $previousAssignee = this.getPreviousAssignee();
        result = result * PRIME + ($previousAssignee == null ? 43 : $previousAssignee.hashCode());
        final java.lang.Object $newAssignee = this.getNewAssignee();
        result = result * PRIME + ($newAssignee == null ? 43 : $newAssignee.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "Escalation(id=" + this.getId() + ", complaint=" + this.getComplaint() + ", escalatedBy=" + this.getEscalatedBy() + ", reason=" + this.getReason() + ", escalatedAt=" + this.getEscalatedAt() + ", previousAssignee=" + this.getPreviousAssignee() + ", newAssignee=" + this.getNewAssignee() + ", resolved=" + this.isResolved() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Escalation() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Escalation(final Long id, final Complaint complaint, final Admin escalatedBy, final String reason, final LocalDateTime escalatedAt, final Admin previousAssignee, final Admin newAssignee, final boolean resolved) {
        this.id = id;
        this.complaint = complaint;
        this.escalatedBy = escalatedBy;
        this.reason = reason;
        this.escalatedAt = escalatedAt;
        this.previousAssignee = previousAssignee;
        this.newAssignee = newAssignee;
        this.resolved = resolved;
    }
}
